In [2]:
import pandas as pd

df = pd.read_csv("data_users.csv")
df

,№,Коммент,Ссылка,Площадка,Подписчики,Тематика блога,Да/Нет,Адрес,ФИО,Телефон,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1,NaN,https://www.instagram.com/gvardis.m?igsh=aHR5Y...,Инстаграм,2765,бьюти/распаковки,Да,"Москва, ул. Дмитрия Ульянова 9/11 к2 кв 11, ин...",Гвардис Мария Александровна,89062150343,...,отметка в сторис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,https://www.instagram.com/bibayka_?igsh=MWkzNm...,Инстаграм,9092,бьюти/лайф,Да,"Город Москва, Складочная 1с13 пн-пт 12.00 - 19.00",Хараламбос Григориос Стураитис,79856376783,...,отметка в сторис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,https://www.instagram.com/maximova.a.a?igsh=bj...,Инстаграм,13000,бьюти/лайф,Да,"Москва, 3-я хорошевская, 21к1, кв.1320",Максимова Анастасия Андреевна,89060213770,...,ряд из сторис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,https://www.instagram.com/as_crimeaa?igsh=bTM1...,Инстаграм,2379,бьюти/лайф,Да,"Севастополь, Руднева 26/А квартира 4 ,299053 И...",Токарева Анастасия Олеговна,89186882606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,https://www.instagram.com/pon.alexa?igsh=MWZwN...,Инстаграм,1705,лайф,Да,"г. Москва, б-р Яна Райниса, д. 37, кв. 35, инд...",Пономарева Александра Чарльзовна,89652542401,...,отметка в сторис,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,NaN,NaN,https://www.instagram.com/lena.bel?igsh=MXR2eG...,Инстаграм,3657,бьюти/лайф,Нет,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,NaN,NaN,https://www.instagram.com/alina.alms?igsh=OGZx...,Инстаграм,15200,лайф,Нет,NaN,хочет в креаторы на постоянку,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,NaN,NaN,https://www.instagram.com/nebalashova?igsh=MXN...,Инстаграм,3165,бьюти/лайф,Нет,NaN,Аллергик,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,NaN,NaN,https://www.instagram.com/ryzh.nika/,Инстаграм,9331,бьюти,Нет,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,NaN,NaN,https://www.instagram.com/litvi_kristina/,Инстаграм,7667,лайф/стилист,Нет,NaN,Аллергик,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
uncols = []

for c in df.columns:
    if c.startswith("Unnamed: "):
        uncols.append(c)
 
uncols.append("№")

In [4]:
df = df.drop(columns=uncols)

In [5]:
df

,Коммент,Ссылка,Площадка,Подписчики,Тематика блога,Да/Нет,Адрес,ФИО,Телефон,Ник в тг,Статус сообщения,Статус бокса,Партия отправки,Дата доставки,Ссылка на обзор
0,NaN,https://www.instagram.com/gvardis.m?igsh=aHR5Y...,Инстаграм,2765,бьюти/распаковки,Да,"Москва, ул. Дмитрия Ульянова 9/11 к2 кв 11, ин...",Гвардис Мария Александровна,89062150343,@gvardis_m,Отправлено,Доставлен,28.11,2.12,NaN
1,NaN,https://www.instagram.com/bibayka_?igsh=MWkzNm...,Инстаграм,9092,бьюти/лайф,Да,"Город Москва, Складочная 1с13 пн-пт 12.00 - 19.00",Хараламбос Григориос Стураитис,79856376783,NaN,Отправлено,Доставлен,28.11,2.12,NaN
2,NaN,https://www.instagram.com/maximova.a.a?igsh=bj...,Инстаграм,13000,бьюти/лайф,Да,"Москва, 3-я хорошевская, 21к1, кв.1320",Максимова Анастасия Андреевна,89060213770,NaN,Отправлено,Доставлен,28.11,2.12,NaN
3,NaN,https://www.instagram.com/as_crimeaa?igsh=bTM1...,Инстаграм,2379,бьюти/лайф,Да,"Севастополь, Руднева 26/А квартира 4 ,299053 И...",Токарева Анастасия Олеговна,89186882606,anastasiyamy,Отправлено,Доставлен,28.11,10.12,NaN
4,NaN,https://www.instagram.com/pon.alexa?igsh=MWZwN...,Инстаграм,1705,лайф,Да,"г. Москва, б-р Яна Райниса, д. 37, кв. 35, инд...",Пономарева Александра Чарльзовна,89652542401,@ponomarevaach,Отправлено,Доставлен,28.11,2.12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,NaN,https://www.instagram.com/lena.bel?igsh=MXR2eG...,Инстаграм,3657,бьюти/лайф,Нет,NaN,NaN,NaN,NaN,Отправлено,Не отправлен,NaN,NaN,NaN
649,NaN,https://www.instagram.com/alina.alms?igsh=OGZx...,Инстаграм,15200,лайф,Нет,NaN,хочет в креаторы на постоянку,NaN,@alinaalms,Отправлено,Не отправлен,NaN,NaN,NaN
650,NaN,https://www.instagram.com/nebalashova?igsh=MXN...,Инстаграм,3165,бьюти/лайф,Нет,NaN,Аллергик,NaN,NaN,Отправлено,Не отправлен,NaN,NaN,NaN
651,NaN,https://www.instagram.com/ryzh.nika/,Инстаграм,9331,бьюти,Нет,NaN,NaN,NaN,NaN,Отправлено,Не отправлен,NaN,NaN,NaN
652,NaN,https://www.instagram.com/litvi_kristina/,Инстаграм,7667,лайф/стилист,Нет,NaN,Аллергик,NaN,NaN,Отправлено,Не отправлен,NaN,NaN,NaN

In [6]:
df_inst = df[df["Площадка"] == "Инстаграм"]

In [7]:
df_inst.to_csv("insta_users.csv", index=False)

In [8]:
list_insts = df_inst["Ссылка"].unique()

In [9]:
list_insts[0]

'https://www.instagram.com/gvardis.m?igsh=aHR5YjBldTJtNzVm'

In [10]:
import os
import re
import json
import argparse
from pathlib import Path
from urllib.parse import urlparse

import requests
from dotenv import load_dotenv

In [12]:
ACTOR_URL = "https://api.apify.com/v2/acts/apify~instagram-profile-scraper/run-sync-get-dataset-items"


def get_username(instagram_url: str) -> str:
    instagram_url = instagram_url.strip()

    if instagram_url.startswith("@"):
        return instagram_url[1:]

    if "instagram.com" not in instagram_url and "/" not in instagram_url:
        return instagram_url

    if not instagram_url.startswith(("http://", "https://")):
        instagram_url = "https://" + instagram_url

    parsed = urlparse(instagram_url)
    parts = [p for p in parsed.path.split("/") if p]

    if not parts:
        raise ValueError("Не смог достать username из ссылки")

    username = parts[0]

    if username in {"p", "reel", "stories", "explore", "accounts"}:
        raise ValueError("Нужна ссылка на профиль, а не на пост/reel/story")

    return username


def safe_name(value: str) -> str:
    value = str(value or "unknown")
    return re.sub(r"[^\w.-]+", "_", value).strip("_")


def run_apify(username: str) -> dict:
    if not APIFY_TOKEN:
        raise RuntimeError("Нет APIFY_TOKEN в .env")

    payload = {
        "usernames": [username],
        "includeAboutSection": False
    }

    response = requests.post(
        ACTOR_URL,
        params={
            "format": "json",
            "clean": "true"
        },
        headers={
            "Authorization": f"Bearer {APIFY_TOKEN}",
            "Content-Type": "application/json"
        },
        json=payload,
        timeout=300
    )

    response.raise_for_status()

    items = response.json()

    if not items:
        raise RuntimeError(f"Apify ничего не вернул по @{username}")

    return items[0]


def is_video(post: dict) -> bool:
    post_type = str(post.get("type", "")).lower()
    product_type = str(post.get("productType", "")).lower()

    return (
        "video" in post_type
        or "reel" in post_type
        or "clips" in product_type
        or bool(post.get("videoUrl"))
        or bool(post.get("videoPlayCount"))
        or bool(post.get("videoViewCount"))
    )


def download_file(url: str, path: Path) -> bool:
    if not url:
        return False

    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://www.instagram.com/"
    }

    try:
        with requests.get(url, headers=headers, stream=True, timeout=120) as r:
            r.raise_for_status()

            path.parent.mkdir(parents=True, exist_ok=True)

            with open(path, "wb") as f:
                for chunk in r.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        f.write(chunk)

        return path.exists() and path.stat().st_size > 0

    except Exception as e:
        print(f"Не скачалось: {url[:80]}...")
        print(f"Ошибка: {e}")
        return False


def normalize_profile(profile: dict, downloaded_videos: list) -> dict:
    return {
        "id": profile.get("id"),
        "username": profile.get("username"),
        "full_name": profile.get("fullName"),
        "followers": profile.get("followersCount"),
        "following": profile.get("followsCount"),
        "posts_count": profile.get("postsCount"),
        "bio": profile.get("biography"),
        "external_url": profile.get("externalUrl"),
        "profile_url": profile.get("url"),
        "profile_pic_url": profile.get("profilePicUrl"),
        "verified": profile.get("verified"),
        "private": profile.get("private"),
        "business_account": profile.get("isBusinessAccount"),
        "business_category": profile.get("businessCategoryName"),
        "videos": downloaded_videos
    }


def save_profile(instagram_url: str, output_root: str = "output") -> Path:
    username = get_username(instagram_url)
    print(f"Парсю @{username}")

    profile = run_apify(username)

    profile_id = profile.get("id") or profile.get("username") or username
    profile_dir = Path(output_root) / safe_name(profile_id)
    videos_dir = profile_dir / "videos"

    profile_dir.mkdir(parents=True, exist_ok=True)
    videos_dir.mkdir(parents=True, exist_ok=True)

    latest_posts = profile.get("latestPosts") or []

    video_posts = [post for post in latest_posts if is_video(post)][:20]

    videos_info = []

    for i, post in enumerate(video_posts, start=1):
        shortcode = post.get("shortCode") or post.get("shortcode") or post.get("id") or f"video_{i}"
        video_url = post.get("videoUrl")

        local_path = None
        ok = False

        # Скачиваем только первые 3 видео
        if i <= 3:
            filename = f"{i:02d}_{safe_name(shortcode)}.mp4"
            local_path = videos_dir / filename
            ok = download_file(video_url, local_path)

        item = {
            "number": i,
            "id": post.get("id"),
            "shortcode": shortcode,
            "post_url": post.get("url") or f"https://www.instagram.com/p/{shortcode}/",
            "caption": post.get("caption"),
            "timestamp": post.get("timestamp"),
            "likes": post.get("likesCount"),
            "comments": post.get("commentsCount"),
            "views": post.get("videoViewCount") or post.get("videoPlayCount") or post.get("viewsCount"),
            "thumbnail": post.get("displayUrl") or post.get("thumbnailUrl"),
            "video_url": video_url,
            "local_path": str(local_path) if ok else None,
            "downloaded": ok
        }

        videos_info.append(item)

        if i <= 3:
            if ok:
                print(f"Скачано: {local_path}")
            else:
                print(f"Не скачалось видео {shortcode}")

    normalized = normalize_profile(profile, videos_info)

    with open(profile_dir / "profile.json", "w", encoding="utf-8") as f:
        json.dump(normalized, f, ensure_ascii=False, indent=2)

    with open(profile_dir / "bio.txt", "w", encoding="utf-8") as f:
        f.write(f"ID: {normalized['id']}\n")
        f.write(f"Username: {normalized['username']}\n")
        f.write(f"Full name: {normalized['full_name']}\n")
        f.write(f"Followers: {normalized['followers']}\n")
        f.write(f"Following: {normalized['following']}\n")
        f.write(f"Posts: {normalized['posts_count']}\n")
        f.write(f"External URL: {normalized['external_url']}\n\n")
        f.write(normalized["bio"] or "")

    print()
    print(f"Готово. Папка: {profile_dir}")

    return profile_dir

In [13]:
url = "https://www.instagram.com/gvardis.m?igsh=aHR5YjBldTJtNzVm"
save_profile(url, "2")

Парсю @gvardis.m
Скачано: 2\5569396957\videos\01_DYo2Eu5NB01.mp4
Скачано: 2\5569396957\videos\02_DYmqfk6Nj8O.mp4
Скачано: 2\5569396957\videos\03_DYmUkzqNjvW.mp4

Готово. Папка: 2\5569396957

WindowsPath('2/5569396957')

In [49]:
inst_dict = {}

for i in range(1, len(list_insts) + 1):
    inst_dict[i] = list_insts[i - 1]

In [51]:
with open("insts.json", "w") as f:
    json.dump(inst_dict, f)

In [16]:
# Чтение словаря из файла
with open('insts.json', 'r', encoding='utf-8') as f:
    inst_dict = json.load(f)

In [17]:
from tqdm.auto import tqdm

In [19]:
inst_dict

{'1': 'https://www.instagram.com/gvardis.m?igsh=aHR5YjBldTJtNzVm',
 '2': 'https://www.instagram.com/bibayka_?igsh=MWkzNmNpNTBqYzkwZQ==',
 '3': 'https://www.instagram.com/maximova.a.a?igsh=bjRpdjJiMmlhdjYz',
 '4': 'https://www.instagram.com/as_crimeaa?igsh=bTM1dnh3YnFxd2Vo',
 '5': 'https://www.instagram.com/pon.alexa?igsh=MWZwNmN5c2dicWsxZA==',
 '6': 'https://www.instagram.com/olesya.nemceva?igsh=MXM3Y21kbTM3cnVqcg%3D%3D&utm_source=qr',
 '7': 'https://www.instagram.com/kate_mom2?igsh=Yjd1MnA3YmMxMGo0&utm_source=qr',
 '8': 'https://www.instagram.com/fructoza.a?igsh=MWp3bWszNHRmcWV3Zw==',
 '9': 'https://www.instagram.com/aammmmm79?igsh=MTR2YTV1dHE2djVxbA%3D%3D&utm_source=qr',
 '10': 'https://www.instagram.com/regina.sii?igsh=eWlmNHUyaWgyZ3Bz',
 '11': 'https://www.instagram.com/blackymuse?igsh=dDg0ZjFycDhpeXc1',
 '12': 'https://www.instagram.com/mn_marunails?igsh=MXYzMnFqZW16azBhYw==',
 '13': 'https://www.instagram.com/rudneva_nel?igsh=MWMyNW5qOTkwNGkycw%3D%3D&utm_source=qr',
 '14': 'https://www.instagram.com/beauty_y000',
 '15': 'https://vt.tiktok.com/ZSPt9jL79   https://www.instagram.com/reel/DSkR057DK3O/?igsh=MTVwampmYTE2b3dpeA==',
 '16': 'https://www.instagram.com/alina.chichikalova/',
 '17': 'https://www.instagram.com/rika.lyalina/',
 '18': 'https://www.instagram.com/l_n_m?igsh=cjNscHloZjhoemEz&utm_source=qr',
 '19': 'https://www.instagram.com/alexa.kulikova?igsh=MWVkb2d0bzYzaWh5aQ==',
 '20': 'https://www.instagram.com/sofis_mua?igsh=bXF5ejNtZnZoMGNj',
 '21': 'https://www.instagram.com/tochaaaaaaaaaa?igsh=MWE1M3p5eDBuajMxcg%3D%3D&utm_source=qr',
 '22': 'https://www.instagram.com/liza.fisher_?igsh=dGo3ZWRmZml0cXcw',
 '23': 'https://www.instagram.com/ooohkeri?igsh=MXJhamkxcnoxYjE1dw%3D%3D&utm_source=qr',
 '24': 'https://www.instagram.com/eellizavettaaa?igsh=cTgzc3c4NWx2Z2Rv',
 '25': 'https://www.instagram.com/sashaleybman?igsh=MTFoYWx1YWU2ZGtmYg==',
 '26': 'https://www.instagram.com/lyyuovy?igsh=MTJpaW43NWRzczNydg==',
 '27': 'https://www.instagram.com/kiryanova.u/reels/',
 '28': 'https://www.instagram.com/ansomova/reels/',
 '29': 'https://www.instagram.com/tanya.proskurina?igsh=Z2JsNXlzczFucGE5',
 '30': 'https://www.instagram.com/pobedinskayya?igsh=MTkxeTE0b2R1NTB6MQ%3D%3D&utm_source=qr',
 '31': 'https://www.instagram.com/ekmyalo?igsh=MTFnYmlzMTN6eHF6ag==',
 '32': 'https://www.instagram.com/bogdanovaanst?igsh=eGZmd2J6cHA5cWU5',
 '33': 'https://www.instagram.com/sashalukyanovaa?igsh=Z3drcWljbmljMDJj',
 '34': 'https://www.instagram.com/usachevanst/',
 '35': 'https://www.instagram.com/dmtkate?igsh=MThtZXU5eXYwZmJvMQ==',
 '36': 'https://www.instagram.com/nikitina_mladshya?igsh=MzR3ZTI5ZndkYnlz',
 '37': 'https://www.instagram.com/vikkkime?igsh=OWlsemNucHcxMnJ3',
 '38': 'https://www.instagram.com/chrissssssss21?igsh=MmEydmh4YndvbHN1',
 '39': 'https://www.instagram.com/katena.astahowa/reels/',
 '40': 'https://www.instagram.com/kathyumnova?igsh=b2Z5Y3kxcmtwYWk1&utm_source=qr',
 '41': 'https://www.instagram.com/kdvmua/',
 '42': 'https://www.instagram.com/v._aliya?igsh=M2ZweDlpa2Jmcnp2',
 '43': 'https://www.instagram.com/lee.aleksandra_?igsh=dDVvZ3Q5czFqOW5n&utm_source=qr',
 '44': 'https://www.instagram.com/kumerinaya?igsh=MTFmdDg0cTlzMGxsMA==',
 '45': 'https://www.instagram.com/tanya_weks?igsh=c3FtNGwyazlweDNu&utm_source=qr',
 '46': 'https://www.instagram.com/magaramova_makeup?igsh=MXZud3d2cWNpNmsxZA==',
 '47': 'https://www.instagram.com/arina_poluyanova/reels/',
 '48': 'https://www.instagram.com/_beauty.sofiu_/',
 '49': 'https://www.instagram.com/aeeelina?igsh=bGZuMG56ejIycHMx',
 '50': 'https://www.instagram.com/karina.botox?igsh=amlzYjJwZGhlZmZu',
 '51': 'https://www.instagram.com/essi.lune?igsh=MWpnbm1rZHRkc2hkdw==',
 '52': 'https://www.instagram.com/valerina_belavina?igsh=MXhyeHJpNG9ubHB0bA==',
 '53': 'https://www.instagram.com/ilaanabanana?igsh=MTlrNjEwYjNpM2RpbQ%3D%3D&utm_source=qr',
 '54': 'https://www.instagram.com/grossman.katerine/',
 '55': 'https://www.instagram.com/elizaabeth_19?igsh=MXRnbnd6NGx1YjU3YQ%3D%3D&utm_source=qr',
 '56': 'https://www.instagram.com/superklassnayaaa?igsh=MWFucWNlNmZzN3RoeA%3D%3D&utm_source=qr',
 '57': 'https://www.instagram.com/aksenskin/',
 '58': 'https://www.instagram.com/mua_mari5?igsh=MXRnb2g4dzA5bWpkdA==',
 '59': 'https://www.instagram.com/masha_caxapp?igsh=bHc3czc1YXVkYmww',
 '60': 'https://www.instagram.com/p/DNQNuDkCJiW/?igsh=MWZ3MHNvOGt4NGE0MA==',
 '61': 'https://www.instagram.com/romaomode?igsh=MTdneGVsOW5rbzlmYw==',
 '62': 'https://www.instagram.com/lisaoutside/#',
 '63': 'https://www.instagram.com/apreleek/#',
 '64': 'https://www.instagram.com/frantsevamua?igsh=MXM5NDh2bmRtMmNoeg==',
 '65': 'https://www.instagram.com/eegorvvva?igsh=M3c5MTNtcmxocXV6',
 '66': 'https://www.instagram.com/annette.nefedova?igsh=b3NkZWRmcjhzeDNh',
 '67': 'https://www.instagram.com/zalevskaya_y?igsh=bHNpc2Vkcm5vbXJq',
 '68': 'https://www.instagram.com/bossygirl_ka/',
 '69': 'https://www.instagram.com/dr.tm54?igsh=MTh5aXU3cm9vemZodA==',
 '70': 'https://www.instagram.com/msv_01_01_01?igsh=ZTFkYmgybDd4bTV3',
 '71': 'https://www.instagram.com/babyskris?igsh=aHAwMGF6emVvZDB1',
 '72': 'https://www.instagram.com/yuliamishkareva?igsh=dGdnNDh4N2llZmIy',
 '73': 'https://www.instagram.com/catrine_gri?igsh=MWp6OGx5ODZkZTliZw==',
 '74': 'https://www.instagram.com/alex_dalines?igsh=dG1qM3NmazVjb3g0',
 '75': 'https://www.instagram.com/valya_____?igsh=MTEyZDA1ZmNnZWN4NA==',
 '76': 'https://www.instagram.com/bari__saparova?igsh=MWRqdXVvcWpyZXNzOA==',
 '77': 'https://www.instagram.com/di.na.naa?igsh=OHlyeW9rYnZkZ25n',
 '78': 'https://www.instagram.com/kristina.emtsevaa?igsh=c3JmaXIxYTFxcXNh',
 '79': 'https://www.instagram.com/tsitlidze_sofia?igsh=MXhpYzQ5amI3NWluZQ==',
 '80': 'https://www.instagram.com/_alexandra_rich_?igsh=MWNzd3RwdHRjbml3MQ==',
 '81': 'https://www.instagram.com/sssscxr___?igsh=b2JqNXNqYTRmc3Fh',
 '82': 'https://www.instagram.com/malllkova?igsh=dGV4MTQyMHlocmZs',
 '83': 'https://www.instagram.com/valeri_salnikova?igsh=MWJlbnpwd3dtZ2JreQ==',
 '84': 'https://www.instagram.com/griffindaash?igsh=Z3M4ZTV6NHl6Z3pq',
 '85': 'https://www.instagram.com/believixx_tv?igsh=dDQyNXZvajBzYXY=',
 '86': 'https://www.instagram.com/liiilyyyaa?igsh=aGxoamlkdzAzb2I5',
 '87': 'https://www.instagram.com/mulya_mulya?igsh=Z2kzZ2Y3NjM4bjFl',
 '88': 'https://www.instagram.com/d.randshel?igsh=MXUxdnZnYml3dDY0ZA==',
 '89': 'https://www.instagram.com/ilchenko_lera?igsh=am0yczdkcmphdWRm',
 '90': 'https://www.instagram.com/za_makeupom?igsh=eGxtaGp1OW55d3Vr',
 '91': 'https://www.instagram.com/maria__samedova?igsh=eWdoMmx5dTg4OWY=',
 '92': 'https://www.instagram.com/tatyana.darm?igsh=dXVyYzQ0Zm43NjB1',
 '93': 'https://www.instagram.com/evochie2003?igsh=bjNmaHp1bGI0aGx2',
 '94': 'https://www.instagram.com/svetlana.laivi?igsh=cGRjcDVyM3I4bnpu',
 '95': 'https://www.instagram.com/caracallis/',
 '96': 'https://www.instagram.com/ulianayarts/',
 '97': 'https://www.instagram.com/beautypolya?igsh=dGZmeXpybnZ6ZjJp',
 '98': 'https://www.instagram.com/_beautysima?igsh=MXh1amFscTBrdHVyMQ==',
 '99': 'https://www.instagram.com/vlada.sys?igsh=MXhlNXdodTBtOGp5YQ==',
 '100': 'https://www.instagram.com/missis.oleynik?igsh=MWxqMnVwdDMydDdtbA==',
 '101': 'https://www.instagram.com/karisha.rii?igsh=bDJ3NGEybG05N2py',
 '102': 'https://www.instagram.com/luukovka?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
 '103': 'https://www.instagram.com/annakorpunova?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
 '104': 'https://www.instagram.com/alenapalace/?utm_source=ig_web_button_share_sheet',
 '105': 'https://www.instagram.com/allalia23?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
 '106': 'https://www.instagram.com/pankfloy?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
 '107': 'https://www.instagram.com/marinetttes?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
 '108': 'https://www.instagram.com/kosacheva.ek?igsh=MWFzaGg5ZWdqODA2ZA==',
 '109': 'https://www.instagram.com/chiki.vikki?igsh=MTF6OHgzNGlvYTZmbA==',
 '110': 'https://www.instagram.com/kobzzzeva?igsh=eDk5aTFxbHU4cGI4',
 '111': 'https://www.instagram.com/lizyweber?igsh=N3k2Y3kxbDA4Nnc1',
 '112': 'https://www.instagram.com/yurieva_yuliya?igsh=MXFnYjIybmEyMXh2NQ==',
 '113': 'https://www.instagram.com/al.alexandrovva?igsh=MWczdXUxajQ3bDB5dw==',
 '114': 'https://www.instagram.com/lwowa.k?igsh=MWpucmR2emdxamloMw==',
 '115': 'https://www.instagram.com/smailinng_?igsh=amJvbXpzZnQwaXkx',
 '116': 'https://www.instagram.com/its.aliiinna?igsh=MTNlbWFmMjBjb2hwZA==',
 '117': 'https://www.instagram.com/nastyavasiiileva?igsh=MXZsbW12N2toenplNQ==',
 '118': 'https://www.instagram.com/fffsonic?igsh=MTBqdzFnNXFlbmNxdg==',
 '119': 'https://www.instagram.com/eevameee?igsh=MW52cDJjZ3Y2cWtqeQ==',
 '120': 'https://www.instagram.com/misdiminor?igsh=MWhsMTFsdzZjcG9sNw==',
 '121': 'https://www.instagram.com/krisbow.me?igsh=MXlrdHZ6eHUxMXN0',
 '122': 'https://www.instagram.com/lyaba_evochka?igsh=MTZ6b2FqamdtZDlpMQ==',
 '123': 'https://www.instagram.com/lerochek.97?igsh=OW56MW1xOXV2YWwx',
 '124': 'сторис',
 '125': 'https://www.instagram.com/limataevaa?igsh=ejBydWNpbGlwdWox',
 '126': 'https://www.instagram.com/viktoris_dd?igsh=MTQzM3FkODRsNzd2Mw==',
 '127': 'https://www.instagram.com/kamilkqs?igsh=aXpnYmVkZHUyMHl2',
 '128': 'https://www.instagram.com/_rusllana__?igsh=MXQwdXJqbXYzaTFxMQ==',
 '129': 'https://www.instagram.com/asia.anima?igsh=MzcwMXVub2ttbmlq',
 '130': 'https://www.instagram.com/ann.tsvetkaaa?igsh=bGEzazFwYjYwcmdy',
 '131': 'https://www.instagram.com/itsaiikaa?igsh=MTJnbzNtbmphZGdsaQ==',
 '132': 'https://www.instagram.com/_madsti_?igsh=MTgwOHg3amN0bG1ubw==',
 '133': 'https://www.instagram.com/kosmanast?igsh=MTZyaWZyajA2aWgxMw==',
 '134': 'https://www.instagram.com/ur.homeland?igsh=MXc4OG5yMzNxcnFkNg==',
 '135': 'https://www.instagram.com/samuraixaa?igsh=c2dmZ3NjZHUyNG1s',
 '136': 'https://www.instagram.com/milkinadi?igsh=dXhvZXc3eTh3OG5i',
 '137': 'https://www.instagram.com/sveta.subbo?igsh=MWkyNGN3MnU2MjFrNA==',
 '138': 'https://www.instagram.com/helen.redfield?igsh=MW0yNGdtOWxqN2VzYg==',
 '139': 'https://www.instagram.com/flaw_rina?igsh=MWt3OXp5ZGMzaWVzaw==',
 '140': 'https://www.instagram.com/ekatyys?igsh=MW4ybWR0cXkxa3h4aA==',
 '141': 'https://www.instagram.com/twixi_twins?igsh=MTlqZjA1bGJjMWFyZA==',
 '142': 'https://www.instagram.com/viktoriaevseevaa?igsh=MWhydGdwOXg0dnpxMg==',
 '143': 'https://www.instagram.com/paalchikovva?igsh=dXNtNDUydnZpbjh3',
 '144': 'https://www.instagram.com/miss.yana.liss?igsh=eXA1NTM0cDNvZ2Yx',
 '145': 'https://www.instagram.com/naturazova?igsh=MXFmYm1zbWdoZW1yMg==',
 '146': 'https://www.instagram.com/di.li.ya_?igsh=MTFjcTNid3Boam0wMw==',
 '147': 'https://www.instagram.com/_olga_purgina_?igsh=M2ZybXVkNXowYmM0',
 '148': 'https://www.instagram.com/joniboy_10?igsh=MW1rdGd0enV4N2t3aA==',
 '149': 'https://www.instagram.com/ottorvaa?igsh=amxwY29jdnJtYzE=',
 '150': 'https://www.instagram.com/rastsvetaii?igsh=dnc5YWV5anR0aHNw',
 '151': 'https://www.instagram.com/maru.tsybulevskaya?igsh=NWJtcHpzaXNoNmdi',
 '152': 'https://www.instagram.com/olinelle.ro?igsh=bngya2NzbGU4MXFv',
 '153': 'https://www.instagram.com/raninen_indira?igsh=MWJsaXJ4ZWczMWEyYg==',
 '154': 'https://www.instagram.com/tasya.viyu_life?igsh=NTQ0bnNqMnA3ZTV1',
 '155': 'https://www.instagram.com/katya.bysinka?igsh=MW95bjU3cHRka2toOA==',
 '156': 'https://www.instagram.com/helen_kayer?igsh=MXR3NzBiODZ2MWRw',
 '157': 'https://www.instagram.com/ksenka.mom?igsh=MTFieTUwa2MxdmRleQ==',
 '158': 'https://www.instagram.com/its.mary.shoppins?igsh=MWRsZ3J2NnNqMTZrZg==',
 '159': 'https://www.instagram.com/nastasidementeva?igsh=MXhrc2MxamV2Mjd0ZA==',
 '160': 'https://www.instagram.com/grustnayaosoba?igsh=Nm1xcng5NWEwa3h5',
 '161': 'https://www.instagram.com/shitova.bayer?igsh=ZDVxNDA1NGVoNWsy',
 '162': 'https://www.instagram.com/marenela_beauty?igsh=eGkweTlqOGJvam1s',
 '163': 'https://www.instagram.com/natalia.lapina_?igsh=NW9iNW8zenFtZ3Ro',
 '164': 'https://www.instagram.com/svetamlg?igsh=cWV4b3AwNzFxdW1w',
 '165': 'https://www.instagram.com/anya___vasina?igsh=ZGk5ejc4N2E3Mno3',
 '166': 'https://www.instagram.com/mordovochka_katrin?igsh=cGFpNGtrMmk2eW5l',
 '167': 'https://www.instagram.com/nikalina_life?igsh=MWJmZWZtejhlYmx6Yw==',
 '168': 'https://www.instagram.com/hi.natasmith?igsh=MTk2bnVieW41bTN4OA==',
 '169': 'https://www.instagram.com/lifaanteva?igsh=Zm5paTRzc2todndh',
 '170': 'https://www.instagram.com/amina_gashimova_?igsh=cWFtYmU3cGxjZjJw',
 '171': 'https://www.instagram.com/evsyukovaaaa?igsh=Y3dqaXA4eDY2eHpv',
 '172': 'https://www.instagram.com/nastasyavays?igsh=MTdieWVjajFhamIxOA==',
 '173': 'Не могу найти кто это аххахх, но топ',
 '174': 'https://www.instagram.com/sashaleybman?igsh=cTFjOXc3YXhieXFj',
 '175': 'https://www.instagram.com/fazanchik?igsh=MXNrNWYwMHlvanR4YQ==',
 '176': 'https://www.instagram.com/dashulyamys?igsh=MWY1dHdibXV0Nmc3dA==',
 '177': 'https://www.instagram.com/layla.blogs?igsh=MXdhaDRweW4ydGZ4Yw==',
 '178': 'https://www.instagram.com/natalie.21020?igsh=dnZ4aHEzbDZhNXd2',
 '179': 'https://www.instagram.com/ellverovera?igsh=MWRrYW5jMHMyYWNrZA==',
 '180': 'https://www.instagram.com/ooshroevaa?igsh=a3o4bGxsMjVrYjM1',
 '181': 'https://www.instagram.com/ereomenko.yu?igsh=MWI4czRqYnNrd2Fxcg==',
 '182': 'https://www.instagram.com/zosssya?igsh=cW1nOWliOXp4Y2li',
 '183': 'https://www.instagram.com/sophia.tibeikina?igsh=MWt1emxsempkaXo1ag==',
 '184': 'https://www.instagram.com/dbebikovaa?igsh=Y3JoOTk0Z2gybDFh',
 '185': 'https://www.instagram.com/veronika.yaburovaa?igsh=YXNjOWgzNXhpM3B5',
 '186': 'https://www.instagram.com/yannadmi?igsh=YTQzczcyeDF0c3gx',
 '187': 'https://www.instagram.com/alinayako?igsh=MWxlMXpwdDN1MGNhcg==',
 '188': 'https://www.instagram.com/serebryakovaa_v?igsh=MXE0NnpkZ2pvOXJvZA==',
 '189': 'https://www.instagram.com/ggviktoria?igsh=c2RoOGlxejJkajZ2',
 '190': 'https://www.instagram.com/podkaura.d?igsh=Z3h1ZDRiYXEwOW9j',
 '191': 'https://www.instagram.com/alina_fedorovaa?igsh=dWxvd2QzYXpkbHR1',
 '192': 'https://www.instagram.com/wifey.liza?igsh=MWU0bWd5cWxzdHNoaA==',
 '193': 'https://www.instagram.com/beauty_vikkki?igsh=MWxlb2FqcTNxZmt4Zw==',
 '194': 'https://www.instagram.com/anutakero?igsh=ZHZrMjloYTlobDlr',
 '195': 'https://www.instagram.com/hoomkka?igsh=MTI1cWo0b3Y3cGZsNQ==',
 '196': 'https://www.instagram.com/katya_emblem?igsh=ejdxOGx1M3Nya3c5',
 '197': 'https://www.instagram.com/vikaremizova?igsh=MWUxZjhkdW91b3Vrcg==',
 '198': 'https://www.instagram.com/nastya.tress?igsh=MXh0MmNqdndvbmliZQ==',
 '199': 'https://www.instagram.com/valerie_aesthetic?igsh=MTRpbTVwc281cWwzdg==',
 '200': 'https://www.instagram.com/breslavskayaa?igsh=MXJ3Z3hnY2N3d2lzeg==',
 '201': 'https://www.instagram.com/sedova13?igsh=emEyZnlnN2Z0bTcw',
 '202': 'https://www.instagram.com/annetdnk?igsh=MXVhanJtbnl4dnpibg==',
 '203': 'https://www.instagram.com/detstvotima_twins?igsh=cWw2aW9ieThiaGI0',
 '204': 'https://www.instagram.com/ksushkincc?igsh=MTQ0YXAxMzhibWViMg==',
 '205': 'https://www.instagram.com/kalistratova.valya?igsh=bW54enFrZjU3ZTgy',
 '206': 'https://www.instagram.com/ilzirekay?igsh=MWtneW5oeHR0eGd4eg==',
 '207': 'https://www.instagram.com/cam.i.i.i.i?igsh=bXJ2OTRydnBucDBs',
 '208': 'https://www.instagram.com/ssavkinalina?igsh=MWNmeDNyajJ0bXV6eA==',
 '209': 'https://www.instagram.com/sabina_sunrise?igsh=MWJ5dnZteHhjYzFhMg==',
 '210': 'https://www.instagram.com/soniamezhkv?igsh=em8yb3U4MWZod3No',
 '211': 'https://www.instagram.com/annfiree?igsh=MWxxeXRqNTdxaHFoYw==',
 '212': 'https://www.instagram.com/pinteresno_blog?igsh=MW92dHFkenBvd3Z2OQ==',
 '213': 'https://www.instagram.com/kurbanova.alinas?igsh=em85b3lwOGN4dHM1',
 '214': 'https://www.instagram.com/vicavictorria?igsh=MXR2a2lmcTA1ZXE4eA==',
 '215': 'https://www.instagram.com/tanner_makeup?igsh=MWg1MzNubnV4M2k5YQ==',
 '216': 'https://www.instagram.com/_helga6?igsh=M2FvM3gyN2p4ZjZy',
 '217': 'https://www.instagram.com/maaargooooo?igsh=ZTgxYnVqNnNtZ2Jo',
 '218': 'https://www.instagram.com/sofia_anilif?igsh=dGxobHRkemdocjZr',
 '219': 'https://www.instagram.com/d_chernysheva_?igsh=MXBwMGRrZWRxMnZudw==',
 '220': 'https://www.instagram.com/the.marri?igsh=YzlwbzVqdGpqODhq',
 '221': 'https://www.instagram.com/nastya.shantal?igsh=dnY2cmt0ajV6OHo1',
 '222': 'https://www.instagram.com/elya_curly?igsh=bGZucnB4MTNvMGM4',
 '223': 'https://www.instagram.com/iri_ivani?igsh=ZnYyeTV0ZWxuMGoz',
 '224': 'https://www.instagram.com/marina_piggy?igsh=ODV5MmdhYWk4bHY=',
 '225': 'https://www.instagram.com/mogilyovas?igsh=eXJ6M2xmaWhqNm1m',
 '226': 'https://www.instagram.com/knyazzheva?igsh=YWV3eWYzZnFwdzJk',
 '227': 'https://www.instagram.com/marrrielka?igsh=MWc2azJ4aGppMWc1bw==',
 '228': 'https://www.instagram.com/anya_fur?igsh=MXhqZGlsbWUweG5qeg==',
 '229': 'https://www.instagram.com/gi_pmu?igsh=OHkybzgybTV6YnVn',
 '230': 'https://www.instagram.com/liliitom?igsh=YXM4cHR4bXM5eXFk',
 '231': 'https://www.instagram.com/yanarcissa?igsh=MXA5bXhmNjBsc21uaQ==',
 '232': 'https://www.instagram.com/a1zizka?igsh=MWt6bW1rdHM4NWp1Mw==',
 '233': 'https://www.instagram.com/ksu.porubleva?igsh=dnR1ejd1M3BjNWxz',
 '234': 'https://www.instagram.com/a.amina.ll?igsh=MW54ZXV5MGg0ZTE3MA==',
 '235': 'https://www.instagram.com/ityasha_?igsh=cTBucXppOWNiZG1i',
 '236': 'https://www.instagram.com/natalirinchuk?igsh=MWx4dTRleWQwZHlucA==',
 '237': 'https://www.instagram.com/tanya_amurskaya?igsh=dTk0bG84eW9mbDB1',
 '238': 'https://www.instagram.com/lisica.pr?igsh=NTcwdWhzNW93a2M0',
 '239': 'https://www.instagram.com/lizashiriaevaa?igsh=dHpwdHNyMzdmY3Bq',
 '240': 'https://www.instagram.com/polli__tattoo?igsh=MWJ0cmdkNWEwaWwxaw==',
 '241': 'https://www.instagram.com/tania_vizage?igsh=MWloaG1qMGtpYTlrMg==',
 '242': 'https://www.instagram.com/mokka.ira/',
 '243': 'https://www.instagram.com/geekkill/',
 '244': 'https://www.instagram.com/dasha.milyutina/',
 '245': 'https://www.instagram.com/sofa.woow/',
 '246': 'https://www.instagram.com/_karinabond_/',
 '247': 'https://www.instagram.com/katusha.brown/',
 '248': 'https://www.instagram.com/alplni/',
 '249': 'https://www.instagram.com/ign.s.i/',
 '250': 'https://www.instagram.com/neladnayaa/',
 '251': 'https://www.instagram.com/plkarter/',
 '252': 'Сторис',
 '253': 'https://www.instagram.com/lucy.araikovna?igsh=bjNlNGRjcnQ2aDQx',
 '254': 'https://www.instagram.com/dariiruse?igsh=cTBlczl6MXIwa3h3',
 '255': 'https://www.instagram.com/lmashytka?igsh=ZHlzdHR6enl4dmZw',
 '256': 'https://www.instagram.com/zotova.vasileva?igsh=cm00MGZ3eWN6Nnpy',
 '257': 'https://www.instagram.com/soffa_blog_?igsh=a3A0NjNiNWpyaTE2',
 '258': 'https://www.instagram.com/ishina_anny/',
 '259': 'https://www.instagram.com/annaviista/',
 '260': 'https://www.instagram.com/darina_zhukovskaia/',
 '261': 'https://www.instagram.com/nasty_fl?igsh=dzEweXY2b3JzamVt',
 '262': 'https://www.instagram.com/allalife.palette?igsh=Nm1ob2p1MWlvcjR5',
 '263': 'https://www.instagram.com/dayana_freigang?igsh=MTFtMWJ4ZGh5cmEwaA==',
 '264': 'https://www.instagram.com/sofi__aaa___?igsh=a2JyaXB6dHJkZ2U1',
 '265': 'https://www.instagram.com/klukwwi?igsh=bTA5YWswYmRkeDRo',
 '266': 'https://www.instagram.com/u._lll_.u?igsh=MWFrZDJkaG5qN3VlZg==',
 '267': 'https://www.instagram.com/gabsabbirova?igsh=MWFyODl3amJybXVwbA==',
 '268': 'https://www.instagram.com/_radadddd_?igsh=bDF3ZXQ4YzQyOGpy',
 '269': 'https://www.instagram.com/v.vikaaaa?igsh=MWtlZ2QxdTh6d3JqYg==',
 '270': 'https://www.instagram.com/nuninaaa?igsh=MTRweGgwY2ljMDR5MA==',
 '271': 'https://www.instagram.com/velleriss?igsh=MWI4Nno3M2ZvZHdrZA==',
 '272': 'https://www.instagram.com/mary.mafin?igsh=MTVwNDQ1N3M5bGw0cg==',
 '273': 'https://www.instagram.com/kisaliza_7?igsh=MWZrdTQ1aW52NzhkMw==',
 '274': 'https://www.instagram.com/lisasaesth?igsh=YTh2eXJudDh2dGZ4',
 '275': 'https://www.instagram.com/alexsandra.karpova?igsh=eXQ0YXp3MDF5Mmhq',
 '276': 'https://www.instagram.com/nastya.dizzy?igsh=Y2w4bm5wYzBuNjc4',
 '277': 'https://www.instagram.com/miraburieva?igsh=d3BtZzF0cjU2bzQy',
 '278': 'https://www.instagram.com/kriv.da?igsh=MXd2ZjBoZmtudGZsaw==',

In [20]:
inst_dict['13']

'https://www.instagram.com/rudneva_nel?igsh=MWMyNW5qOTkwNGkycw%3D%3D&utm_source=qr'

In [21]:
for key, value in tqdm(inst_dict.items()):
    save_profile(value, key)

  0%|          | 0/419 [00:00<?, ?it/s]

Парсю @gvardis.m
Скачано: 1\5569396957\videos\01_DYo2Eu5NB01.mp4
Скачано: 1\5569396957\videos\02_DYmqfk6Nj8O.mp4
Скачано: 1\5569396957\videos\03_DYmUkzqNjvW.mp4

Готово. Папка: 1\5569396957
Парсю @bibayka_

Готово. Папка: 2\bibayka
Парсю @maximova.a.a
Скачано: 3\21754635456\videos\01_DYeklMoqm2-.mp4
Скачано: 3\21754635456\videos\02_DYZDAIKqjLB.mp4
Скачано: 3\21754635456\videos\03_DYXPBLgRPCj.mp4

Готово. Папка: 3\21754635456
Парсю @as_crimeaa
Скачано: 4\58159981827\videos\01_DQd3U-xDKqK.mp4
Скачано: 4\58159981827\videos\02_DYpnH8fsMdN.mp4
Скачано: 4\58159981827\videos\03_DYpKwudMmON.mp4

Готово. Папка: 4\58159981827
Парсю @pon.alexa
Скачано: 5\53579029361\videos\01_DVGRuENjd-d.mp4
Скачано: 5\53579029361\videos\02_DSXk7QeiDtZ.mp4
Скачано: 5\53579029361\videos\03_DPUCkwCjcQ0.mp4

Готово. Папка: 5\53579029361
Парсю @olesya.nemceva
Скачано: 6\468094400\videos\01_DYnPTJis3-c.mp4
Скачано: 6\468094400\videos\02_DYfXIMxsteZ.mp4
Скачано: 6\468094400\videos\03_DYaPqyWsw7X.mp4

Готово. Папка: 6\468094400
Парсю @kate_mom2
Скачано: 7\3685356465\videos\01_DYKYKeLwF6P.mp4
Скачано: 7\3685356465\videos\02_DXeFER8jQRo.mp4
Скачано: 7\3685356465\videos\03_DWq8Bj6j8uS.mp4

Готово. Папка: 7\3685356465
Парсю @fructoza.a
Скачано: 8\5577474779\videos\01_DYrkmbDsboK.mp4
Скачано: 8\5577474779\videos\02_DYpYsUmMtZT.mp4
Скачано: 8\5577474779\videos\03_DYmt5kyMb5.mp4

Готово. Папка: 8\5577474779
Парсю @aammmmm79
Скачано: 9\65128479754\videos\01_DUYrbqyiLI-.mp4
Скачано: 9\65128479754\videos\02_DUYqsq1iDeo.mp4
Скачано: 9\65128479754\videos\03_DUTX2ZljLrk.mp4

Готово. Папка: 9\65128479754
Парсю @regina.sii
Скачано: 10\74723982122\videos\01_DVZRTsPjTMp.mp4
Скачано: 10\74723982122\videos\02_DYiBT1HtrFI.mp4
Скачано: 10\74723982122\videos\03_DYehak8tYEJ.mp4

Готово. Папка: 10\74723982122
Парсю @blackymuse
Скачано: 11\603286916\videos\01_DSIR6t7CJP0.mp4
Скачано: 11\603286916\videos\02_Cw5wDA6NRTj.mp4
Скачано: 11\603286916\videos\03_DYqIXvlpX-g.mp4

Готово. Папка: 11\603286916
Парсю @mn_marunails
Скачано: 12\16266888913\videos\01_DHiD2NjNeqt.mp4
Скачано: 12\16266888913\videos\02_DQRa-hkjI6y.mp4
Скачано: 12\16266888913\videos\03_DIs0sJUNXTi.mp4

Готово. Папка: 12\16266888913
Парсю @rudneva_nel

Готово. Папка: 13\rudneva_nel
Парсю @beauty_y000
Скачано: 14\17530825189\videos\01_DYZ-6tuNr3r.mp4
Скачано: 14\17530825189\videos\02_DYZ-TutthzD.mp4
Скачано: 14\17530825189\videos\03_DYZ9O8xtov6.mp4

Готово. Папка: 14\17530825189
Парсю @ZSPt9jL79   https:

Готово. Папка: 15\ZSPt9jL79_20_20_20https
Парсю @alina.chichikalova
Скачано: 16\62463700056\videos\01_DW6EUlPiA1i.mp4
Скачано: 16\62463700056\videos\02_DYjQ2pTIPQS.mp4
Скачано: 16\62463700056\videos\03_DYhp1dGIV-c.mp4

Готово. Папка: 16\62463700056
Парсю @rika.lyalina
Скачано: 17\1718739572\videos\01_DX6EvUaxFFN.mp4
Скачано: 17\1718739572\videos\02_DXb9MYMmYT5.mp4
Скачано: 17\1718739572\videos\03_DWsyG3VjpC0.mp4

Готово. Папка: 17\1718739572
Парсю @l_n_m
Скачано: 18\2281313452\videos\01_DN4w4I9Dv4w.mp4
Скачано: 18\2281313452\videos\02_Cy4l6bDKGtS.mp4
Скачано: 18\2281313452\videos\03_DYoIAmDCudJ.mp4

Готово. Папка: 18\2281313452
Парсю @alexa.kulikova
Скачано: 19\286822515\videos\01_DQcWTL4kcn0.mp4
Скачано: 19\286822515\videos\02_DReoygxDAak.mp4
Скачано: 19\286822515\videos\03_DYbiODvMYUr.mp4

Готово. Папка: 19\286822515
Парсю @sofis_mua
Скачано: 20\10589308518\videos\01_DL5ipG7MLR0.mp4

Готово. Папка: 20\10589308518
Парсю @tochaaaaaaaaaa
Скачано: 21\12578455542\videos\01_DRAGae0CMjX.mp4
Скачано: 21\12578455542\videos\02_DUMADOoDZQo.mp4
Скачано: 21\12578455542\videos\03_DQWGTUjDQWJ.mp4

Готово. Папка: 21\12578455542
Парсю @liza.fisher_
Скачано: 22\292668047\videos\01_DWUcnq1js-o.mp4
Скачано: 22\292668047\videos\02_DWMDQOJjE2f.mp4
Скачано: 22\292668047\videos\03_DWLpuWcDeSl.mp4

Готово. Папка: 22\292668047
Парсю @ooohkeri
Скачано: 23\12798669057\videos\01_DT0s7Fvii4D.mp4
Скачано: 23\12798669057\videos\02_DSXIQyvCnPV.mp4
Скачано: 23\12798669057\videos\03_DRWbkGKCpdH.mp4

Готово. Папка: 23\12798669057
Парсю @eellizavettaaa
Скачано: 24\6785221888\videos\01_DYsXAWJsU8q.mp4
Скачано: 24\6785221888\videos\02_DYsW5EzMMZL.mp4
Скачано: 24\6785221888\videos\03_DYsPK3aMzO9.mp4

Готово. Папка: 24\6785221888
Парсю @sashaleybman

Готово. Папка: 25\sashaleybman
Парсю @lyyuovy
Скачано: 26\20427880882\videos\01_DNkIFFas265.mp4
Скачано: 26\20427880882\videos\02_DYowV9PscTr.mp4
Скачано: 26\20427880882\videos\03_DYmp206M9nn.mp4

Готово. Папка: 26\20427880882
Парсю @kiryanova.u
Скачано: 27\1253761287\videos\01_DVKt0WODC8S.mp4
Скачано: 27\1253761287\videos\02_DYpKbimMV7H.mp4
Скачано: 27\1253761287\videos\03_DYlje8Ss1mr.mp4

Готово. Папка: 27\1253761287
Парсю @ansomova
Скачано: 28\4772256129\videos\01_DYrw4LkMBK0.mp4
Скачано: 28\4772256129\videos\02_DYp9b5rtFCr.mp4
Скачано: 28\4772256129\videos\03_DYphnhat4NN.mp4

Готово. Папка: 28\4772256129
Парсю @tanya.proskurina
Скачано: 29\61707973143\videos\01_DYrAVSptZDG.mp4
Скачано: 29\61707973143\videos\02_DYoodRetdOf.mp4
Скачано: 29\61707973143\videos\03_DYmHKYitv1A.mp4

Готово. Папка: 29\61707973143
Парсю @pobedinskayya
Скачано: 30\1558296793\videos\01_DWW2QFyBJia.mp4
Скачано: 30\1558296793\videos\02_DVrxMhrCOXO.mp4
Скачано: 30\1558296793\videos\03_DVl04e0DYO9.mp4

Готово. Папка: 30\1558296793
Парсю @ekmyalo
Скачано: 31\174857101\videos\01_DYruxV0IB83.mp4
Скачано: 31\174857101\videos\02_DYpL1WRhLVA.mp4
Скачано: 31\174857101\videos\03_DYmnFmdBQvb.mp4

Готово. Папка: 31\174857101
Парсю @bogdanovaanst
Скачано: 32\572917784\videos\01_DYkFYvAxEMp.mp4
Скачано: 32\572917784\videos\02_DYhMBBqxjps.mp4
Скачано: 32\572917784\videos\03_DX81K3JRsUH.mp4

Готово. Папка: 32\572917784
Парсю @sashalukyanovaa
Скачано: 33\1426097279\videos\01_DYruDqAodOo.mp4
Скачано: 33\1426097279\videos\02_DYptk6Lob-Y.mp4
Скачано: 33\1426097279\videos\03_DYo4JFyIjzp.mp4

Готово. Папка: 33\1426097279
Парсю @usachevanst
Скачано: 34\73060929351\videos\01_DYsaioDidga.mp4
Скачано: 34\73060929351\videos\02_DYp2KHOi5ds.mp4
Скачано: 34\73060929351\videos\03_DYpsYDyij71.mp4

Готово. Папка: 34\73060929351
Парсю @dmtkate
Скачано: 35\1436245013\videos\01_DYU0ItciXx2.mp4
Скачано: 35\1436245013\videos\02_DYHvEQYix52.mp4
Скачано: 35\1436245013\videos\03_DYCozS_CYJN.mp4

Готово. Папка: 35\1436245013
Парсю @nikitina_mladshya
Скачано: 36\1489465838\videos\01_DVx-Tu4AnRD.mp4
Скачано: 36\1489465838\videos\02_DVqyoPFgnWJ.mp4
Скачано: 36\1489465838\videos\03_DVqBnP-gvJf.mp4

Готово. Папка: 36\1489465838
Парсю @vikkkime
Скачано: 37\67900817450\videos\01_DYrh-RNO4xw.mp4
Скачано: 37\67900817450\videos\02_DYpS6hxMV-Z.mp4
Скачано: 37\67900817450\videos\03_DYm6fqhsBkZ.mp4

Готово. Папка: 37\67900817450
Парсю @chrissssssss21
Скачано: 38\1442376000\videos\01_DO75afSk9dN.mp4
Скачано: 38\1442376000\videos\02_DOqFTNViCAs.mp4
Скачано: 38\1442376000\videos\03_DN5RE7wiI0Z.mp4

Готово. Папка: 38\1442376000
Парсю @katena.astahowa
Скачано: 39\4013884722\videos\01_DYm8rmWMPkp.mp4
Скачано: 39\4013884722\videos\02_DYjQq-2Nq5o.mp4
Скачано: 39\4013884722\videos\03_DYiHcDpN1vE.mp4

Готово. Папка: 39\4013884722
Парсю @kathyumnova
Скачано: 40\56701768113\videos\01_DYpGyttsdy7.mp4
Скачано: 40\56701768113\videos\02_DYo9BTMII8K.mp4
Скачано: 40\56701768113\videos\03_DYl6ZEnugSf.mp4

Готово. Папка: 40\56701768113
Парсю @kdvmua
Скачано: 41\4361641296\videos\01_DYZnDZ2MFk7.mp4
Скачано: 41\4361641296\videos\02_DYSFb_Ts2CU.mp4
Скачано: 41\4361641296\videos\03_DYHOmr8MVec.mp4

Готово. Папка: 41\4361641296
Парсю @v._aliya
Скачано: 42\1576850580\videos\01_DXyvts0NY4b.mp4
Скачано: 42\1576850580\videos\02_DXg7Q1zjBSl.mp4
Скачано: 42\1576850580\videos\03_DXBX6vIhTeY.mp4

Готово. Папка: 42\1576850580
Парсю @lee.aleksandra_
Скачано: 43\3471915720\videos\01_DYrxlIasWhF.mp4
Скачано: 43\3471915720\videos\02_DYjQ0XtsvY3.mp4
Скачано: 43\3471915720\videos\03_DYbpipQsuxU.mp4

Готово. Папка: 43\3471915720
Парсю @kumerinaya

Готово. Папка: 44\kumerinaya
Парсю @tanya_weks
Скачано: 45\1187125746\videos\01_DVVqiV1oA0z.mp4
Скачано: 45\1187125746\videos\02_DVFwTEWjN0E.mp4
Скачано: 45\1187125746\videos\03_DUxLe6ICOmI.mp4

Готово. Папка: 45\1187125746
Парсю @magaramova_makeup
Скачано: 46\5647460924\videos\01_DWw5C5ejpL8.mp4
Скачано: 46\5647460924\videos\02_DYkvq29q7AI.mp4
Скачано: 46\5647460924\videos\03_DYhY1mNKjoe.mp4

Готово. Папка: 46\5647460924
Парсю @arina_poluyanova
Скачано: 47\1650939215\videos\01_DYsZUSoNg6s.mp4
Скачано: 47\1650939215\videos\02_DYnKxMAt-2D.mp4
Скачано: 47\1650939215\videos\03_DYj9NVoN8dd.mp4

Готово. Папка: 47\1650939215
Парсю @_beauty.sofiu_
Скачано: 48\13599002996\videos\01_DSMvZ3qjMD3.mp4
Скачано: 48\13599002996\videos\02_DSJ2Qa5DPV4.mp4
Скачано: 48\13599002996\videos\03_DRtbReADIUK.mp4

Готово. Папка: 48\13599002996
Парсю @aeeelina
Скачано: 49\1352420056\videos\01_DW9h8mYiIj1.mp4
Скачано: 49\1352420056\videos\02_DWwRko3iJ8m.mp4

Готово. Папка: 49\1352420056
Парсю @karina.botox
Скачано: 50\54806015134\videos\01_DUyAb02CP_w.mp4
Скачано: 50\54806015134\videos\02_DYor1qVNKZk.mp4
Скачано: 50\54806015134\videos\03_DYkP8uttXZ2.mp4

Готово. Папка: 50\54806015134
Парсю @essi.lune
Скачано: 51\64853864576\videos\01_DXzhDb9SsBl.mp4
Скачано: 51\64853864576\videos\02_DXuTtjAjHXe.mp4
Скачано: 51\64853864576\videos\03_DWWQcTvErc8.mp4

Готово. Папка: 51\64853864576
Парсю @valerina_belavina
Скачано: 52\3919449165\videos\01_DUBEk40DIIn.mp4
Скачано: 52\3919449165\videos\02_DTp7oT5DHLs.mp4
Скачано: 52\3919449165\videos\03_DYrcrVus98-.mp4

Готово. Папка: 52\3919449165
Парсю @ilaanabanana
Скачано: 53\3082368318\videos\01_DYi8rPlIXK7.mp4
Скачано: 53\3082368318\videos\02_DYckp6ioe-a.mp4
Скачано: 53\3082368318\videos\03_DYCAz_woTqY.mp4

Готово. Папка: 53\3082368318
Парсю @grossman.katerine
Скачано: 54\29794396239\videos\01_DYmaXDIst64.mp4
Скачано: 54\29794396239\videos\02_DYkM0LiMI_I.mp4
Скачано: 54\29794396239\videos\03_DYgb6kWsbba.mp4

Готово. Папка: 54\29794396239
Парсю @elizaabeth_19
Скачано: 55\900833850\videos\01_DYpqk4EMkEo.mp4
Скачано: 55\900833850\videos\02_DYq8CO7MDv1.mp4
Скачано: 55\900833850\videos\03_DYoRn9rMo6J.mp4

Готово. Папка: 55\900833850
Парсю @superklassnayaaa
Скачано: 56\10965095487\videos\01_DSfDXo8Ddm3.mp4
Скачано: 56\10965095487\videos\02_DYrSXSPNBS2.mp4
Скачано: 56\10965095487\videos\03_DYmLz_HtbFJ.mp4

Готово. Папка: 56\10965095487
Парсю @aksenskin
Скачано: 57\877673500\videos\01_DYUeXJsodF7.mp4
Скачано: 57\877673500\videos\02_DXZ71l1Dnby.mp4
Скачано: 57\877673500\videos\03_DW8nGOuiKTV.mp4

Готово. Папка: 57\877673500
Парсю @mua_mari5
Скачано: 58\72678205444\videos\01_DYr8Rccsbjy.mp4
Скачано: 58\72678205444\videos\02_DYr7adCMaaL.mp4
Скачано: 58\72678205444\videos\03_DYrSXmzMs8r.mp4

Готово. Папка: 58\72678205444
Парсю @masha_caxapp
Скачано: 59\73209949843\videos\01_DXejc3QjIOI.mp4
Скачано: 59\73209949843\videos\02_DSdKtFAjGvq.mp4
Скачано: 59\73209949843\videos\03_DSZVK5-DCa5.mp4

Готово. Папка: 59\73209949843

ValueError: Нужна ссылка на профиль, а не на пост/reel/story

In [26]:
inst_dict['61']

'https://www.instagram.com/romaomode?igsh=MTdneGVsOW5rbzlmYw=='

In [29]:
for i in tqdm(range(61, 419)):
    save_profile(inst_dict[str(i)], str(i))

  0%|          | 0/358 [00:00<?, ?it/s]

Парсю @romaomode
Скачано: 61\355672960\videos\01_DYsaJpxoIfQ.mp4
Скачано: 61\355672960\videos\02_DYrJJkJoof0.mp4
Скачано: 61\355672960\videos\03_DYogbX9INTU.mp4

Готово. Папка: 61\355672960
Парсю @lisaoutside
Скачано: 62\6415750517\videos\01_DYo32CiIsns.mp4
Скачано: 62\6415750517\videos\02_DYnACuEowxc.mp4
Скачано: 62\6415750517\videos\03_DYkF2nliD3V.mp4

Готово. Папка: 62\6415750517
Парсю @apreleek
Скачано: 63\814536019\videos\01_DYrJbC_KZ1i.mp4
Скачано: 63\814536019\videos\02_DYpykqksNlY.mp4
Скачано: 63\814536019\videos\03_DNdDmMYoLTh.mp4

Готово. Папка: 63\814536019
Парсю @frantsevamua
Скачано: 64\5771596185\videos\01_DRurAWXDOU3.mp4
Скачано: 64\5771596185\videos\02_CSJFt9dADF1.mp4
Скачано: 64\5771596185\videos\03_DYsa4hFI0mr.mp4

Готово. Папка: 64\5771596185
Парсю @eegorvvva
Скачано: 65\2621427717\videos\01_DVymRELDS4C.mp4
Скачано: 65\2621427717\videos\02_DVymAzUDY0M.mp4
Скачано: 65\2621427717\videos\03_DVti440De1t.mp4

Готово. Папка: 65\2621427717
Парсю @annette.nefedova
Скачано: 66\39434545830\videos\01_DYrBxQNspXB.mp4
Скачано: 66\39434545830\videos\02_DYbjwb4s7ds.mp4
Скачано: 66\39434545830\videos\03_DYY6KFAM1JU.mp4

Готово. Папка: 66\39434545830
Парсю @zalevskaya_y
Скачано: 67\1162943187\videos\01_DWnlXoQioHj.mp4
Скачано: 67\1162943187\videos\02_DYrdXyAOmBV.mp4
Скачано: 67\1162943187\videos\03_DYoytBHOsZ7.mp4

Готово. Папка: 67\1162943187
Парсю @bossygirl_ka
Скачано: 68\8621941709\videos\01_DYoVjU3Otaa.mp4
Скачано: 68\8621941709\videos\02_DYUsPz8g9fu.mp4
Скачано: 68\8621941709\videos\03_DYPt6alAgRG.mp4

Готово. Папка: 68\8621941709
Парсю @dr.tm54
Скачано: 69\15998337906\videos\01_DYM4gCGtlRG.mp4
Скачано: 69\15998337906\videos\02_DX2FEdINWpB.mp4
Скачано: 69\15998337906\videos\03_DQroeYHjT3w.mp4

Готово. Папка: 69\15998337906
Парсю @msv_01_01_01
Скачано: 70\4254715688\videos\01_DYhXyAQsJft.mp4
Скачано: 70\4254715688\videos\02_DYfU1hNTttk.mp4
Скачано: 70\4254715688\videos\03_DYcxQlzy_xR.mp4

Готово. Папка: 70\4254715688
Парсю @babyskris
Скачано: 71\7140940460\videos\01_DYrq7NKijBu.mp4
Скачано: 71\7140940460\videos\02_DYZzZ3-C8A8.mp4
Скачано: 71\7140940460\videos\03_DYXZ2A4iEvb.mp4

Готово. Папка: 71\7140940460
Парсю @yuliamishkareva
Скачано: 72\7205439258\videos\01_DVG9WtNDF-9.mp4

Готово. Папка: 72\7205439258
Парсю @catrine_gri
Скачано: 73\4432303639\videos\01_DYeehpusC2j.mp4
Скачано: 73\4432303639\videos\02_DYVCNc7MeGc.mp4
Скачано: 73\4432303639\videos\03_DYU8s0eMZvV.mp4

Готово. Папка: 73\4432303639
Парсю @alex_dalines
Скачано: 74\402016864\videos\01_DSPXrEDjYEG.mp4
Скачано: 74\402016864\videos\02_DUJE5thjeFw.mp4
Скачано: 74\402016864\videos\03_DYmkGOYN6G1.mp4

Готово. Папка: 74\402016864
Парсю @valya_____
Скачано: 75\6140936135\videos\01_DYnnHMiIZSk.mp4
Скачано: 75\6140936135\videos\02_DYkyL1jopp5.mp4
Скачано: 75\6140936135\videos\03_DX4494komnh.mp4

Готово. Папка: 75\6140936135
Парсю @bari__saparova
Скачано: 76\49733701954\videos\01_DYmGtWvMfCI.mp4
Скачано: 76\49733701954\videos\02_DYeKAJIMyGq.mp4
Скачано: 76\49733701954\videos\03_DYczcBSM1d9.mp4

Готово. Папка: 76\49733701954
Парсю @di.na.naa
Скачано: 77\926397887\videos\01_DYUR9OPCaDZ.mp4
Скачано: 77\926397887\videos\02_DYM0hpjC4Mz.mp4
Скачано: 77\926397887\videos\03_DXbLFGlgorr.mp4

Готово. Папка: 77\926397887
Парсю @kristina.emtsevaa
Скачано: 78\35543238639\videos\01_DMfiW4QqVP-.mp4
Скачано: 78\35543238639\videos\02_DReM3DrDL5f.mp4
Скачано: 78\35543238639\videos\03_DL-I8bRKvqL.mp4

Готово. Папка: 78\35543238639
Парсю @tsitlidze_sofia

Готово. Папка: 79\tsitlidze_sofia
Парсю @_alexandra_rich_
Скачано: 80\1806179130\videos\01_DHC7s4sIMYr.mp4
Скачано: 80\1806179130\videos\02_DYrAMloooOT.mp4
Скачано: 80\1806179130\videos\03_DXES704DCR5.mp4

Готово. Папка: 80\1806179130
Парсю @sssscxr___

Готово. Папка: 81\sssscxr
Парсю @malllkova
Скачано: 82\4255805589\videos\01_DYi9HGHM7T9.mp4
Скачано: 82\4255805589\videos\02_DYhMnqSsO6i.mp4
Скачано: 82\4255805589\videos\03_DYfSdw-MVDs.mp4

Готово. Папка: 82\4255805589
Парсю @valeri_salnikova
Скачано: 83\77867045893\videos\01_DYpzPJAucmI.mp4
Скачано: 83\77867045893\videos\02_DYe7VuLMA9s.mp4
Скачано: 83\77867045893\videos\03_DYbvdVIOeC3.mp4

Готово. Папка: 83\77867045893
Парсю @griffindaash
Скачано: 84\1414481271\videos\01_DYnAIe-RYeB.mp4
Скачано: 84\1414481271\videos\02_DYl_JHGJaFT.mp4
Скачано: 84\1414481271\videos\03_DYkPxoyRHys.mp4

Готово. Папка: 84\1414481271
Парсю @believixx_tv
Скачано: 85\420255561\videos\01_DXFdaaqEtj7.mp4
Скачано: 85\420255561\videos\02_DYrppCKKWYR.mp4
Скачано: 85\420255561\videos\03_DYn8UXHq3dK.mp4

Готово. Папка: 85\420255561
Парсю @liiilyyyaa
Скачано: 86\62578649320\videos\01_DVCu2brjPK6.mp4
Скачано: 86\62578649320\videos\02_DR9amQiDA5D.mp4
Скачано: 86\62578649320\videos\03_DYZ2JMYvYWL.mp4

Готово. Папка: 86\62578649320
Парсю @mulya_mulya
Скачано: 87\512445031\videos\01_DYsJ4rzMsr7.mp4
Скачано: 87\512445031\videos\02_DYmwSx8sQfw.mp4
Скачано: 87\512445031\videos\03_DYaLVeVMHBL.mp4

Готово. Папка: 87\512445031
Парсю @d.randshel
Скачано: 88\79889673184\videos\01_DVJjarrDKET.mp4
Скачано: 88\79889673184\videos\02_DVJhpi-jN-F.mp4

Готово. Папка: 88\79889673184
Парсю @ilchenko_lera
Скачано: 89\570954398\videos\01_DYrX_8htpBj.mp4
Скачано: 89\570954398\videos\02_DYMrbqqMO-l.mp4
Скачано: 89\570954398\videos\03_DXyrqeONsTg.mp4

Готово. Папка: 89\570954398
Парсю @za_makeupom
Скачано: 90\48858941866\videos\01_DL9tGBeoONl.mp4
Скачано: 90\48858941866\videos\02_CyVs9netwTT.mp4
Скачано: 90\48858941866\videos\03_CylCJFAN17p.mp4

Готово. Папка: 90\48858941866
Парсю @maria__samedova
Скачано: 91\334418190\videos\01_DYjlxyosIVD.mp4
Скачано: 91\334418190\videos\02_DYhqPYIsjkX.mp4
Скачано: 91\334418190\videos\03_DYezhLis58D.mp4

Готово. Папка: 91\334418190
Парсю @tatyana.darm
Скачано: 92\2309150156\videos\01_DYWzoVRtdQy.mp4
Скачано: 92\2309150156\videos\02_DYUuRxdsXhy.mp4

Готово. Папка: 92\2309150156
Парсю @evochie2003
Скачано: 93\67062974205\videos\01_DYrxbQxMBXJ.mp4
Скачано: 93\67062974205\videos\02_DYkgrtlMfqz.mp4
Скачано: 93\67062974205\videos\03_DYhZ8ZDxLJ-.mp4

Готово. Папка: 93\67062974205
Парсю @svetlana.laivi
Скачано: 94\10571979188\videos\01_DYmFiaONZpO.mp4
Скачано: 94\10571979188\videos\02_DYjixJdtAIS.mp4
Скачано: 94\10571979188\videos\03_DYex4wetPtK.mp4

Готово. Папка: 94\10571979188
Парсю @caracallis
Скачано: 95\610094615\videos\01_DYh-R9YKy2S.mp4
Скачано: 95\610094615\videos\02_DYX9y_LKY4o.mp4
Скачано: 95\610094615\videos\03_DYQGszFOyfU.mp4

Готово. Папка: 95\610094615
Парсю @ulianayarts
Скачано: 96\247077814\videos\01_DYjFxpXCRG5.mp4
Скачано: 96\247077814\videos\02_DYhoJbFCmMp.mp4
Скачано: 96\247077814\videos\03_DYgit4tCKcu.mp4

Готово. Папка: 96\247077814
Парсю @beautypolya
Скачано: 97\51120945173\videos\01_DYoxteft-6c.mp4
Скачано: 97\51120945173\videos\02_DYsORurNJRE.mp4
Скачано: 97\51120945173\videos\03_DYrpqf6pAn9.mp4

Готово. Папка: 97\51120945173
Парсю @_beautysima
Скачано: 98\18277681311\videos\01_DYsRb7WtXYg.mp4
Скачано: 98\18277681311\videos\02_DYr_jT4t-Ww.mp4
Скачано: 98\18277681311\videos\03_DYphzykNVw0.mp4

Готово. Папка: 98\18277681311
Парсю @vlada.sys
Скачано: 99\1598919106\videos\01_DYHEcUCoP1h.mp4
Скачано: 99\1598919106\videos\02_DX9Lu0MIp3e.mp4
Скачано: 99\1598919106\videos\03_DXjVwfsCBbs.mp4

Готово. Папка: 99\1598919106
Парсю @missis.oleynik
Скачано: 100\1418183695\videos\01_DYol_8Ts261.mp4
Скачано: 100\1418183695\videos\02_DYmDcvJsMCf.mp4
Скачано: 100\1418183695\videos\03_DYli_SOqXIT.mp4

Готово. Папка: 100\1418183695
Парсю @karisha.rii
Скачано: 101\50979109778\videos\01_DYsCjW-uxdh.mp4
Скачано: 101\50979109778\videos\02_DYrU5XSKCAP.mp4
Скачано: 101\50979109778\videos\03_DYpBJgyuiBc.mp4

Готово. Папка: 101\50979109778
Парсю @luukovka
Скачано: 102\5912029361\videos\01_DYrOzuiBbtE.mp4
Скачано: 102\5912029361\videos\02_DYozyw6vA8H.mp4
Скачано: 102\5912029361\videos\03_DYmB3IrOYgN.mp4

Готово. Папка: 102\5912029361
Парсю @annakorpunova
Скачано: 103\50223824794\videos\01_DYsDiBAsCTS.mp4
Скачано: 103\50223824794\videos\02_DYotTDrsY3l.mp4
Скачано: 103\50223824794\videos\03_DYmIiHNM5MI.mp4

Готово. Папка: 103\50223824794
Парсю @alenapalace

Готово. Папка: 104\alenapalace
Парсю @allalia23
Скачано: 105\63032150039\videos\01_DTI9xEAkj_Q.mp4
Скачано: 105\63032150039\videos\02_DNbDGS-o7uU.mp4
Скачано: 105\63032150039\videos\03_DAWEuqxSgqM.mp4

Готово. Папка: 105\63032150039
Парсю @pankfloy
Скачано: 106\4425999692\videos\01_DYscSNbyjD6.mp4
Скачано: 106\4425999692\videos\02_DYpzikEyTVm.mp4
Скачано: 106\4425999692\videos\03_DYnRc1OSdTh.mp4

Готово. Папка: 106\4425999692
Парсю @marinetttes
Скачано: 107\78903849403\videos\01_DYdDTnqAv7C.mp4
Скачано: 107\78903849403\videos\02_DX9RsOUN9hj.mp4
Скачано: 107\78903849403\videos\03_DX7Koe0N6wL.mp4

Готово. Папка: 107\78903849403
Парсю @kosacheva.ek
Скачано: 108\68355067142\videos\01_DYsEEEdNncF.mp4
Скачано: 108\68355067142\videos\02_DYsBMsBt8ky.mp4
Скачано: 108\68355067142\videos\03_DYpmCztO0tv.mp4

Готово. Папка: 108\68355067142
Парсю @chiki.vikki
Скачано: 109\59203579935\videos\01_DQ3XfLriFgA.mp4
Скачано: 109\59203579935\videos\02_DYNnmgAihSv.mp4
Скачано: 109\59203579935\videos\03_DYrKoDaC_Y8.mp4

Готово. Папка: 109\59203579935
Парсю @kobzzzeva
Скачано: 110\1520217374\videos\01_DUEMUBijWah.mp4
Скачано: 110\1520217374\videos\02_DUEE9GhjaTH.mp4
Скачано: 110\1520217374\videos\03_DUD936aDZb7.mp4

Готово. Папка: 110\1520217374
Парсю @lizyweber
Скачано: 111\2421252983\videos\01_DYsRvOFqaXd.mp4
Скачано: 111\2421252983\videos\02_DYoddN1Kpy3.mp4
Скачано: 111\2421252983\videos\03_DYmTk4zKkRK.mp4

Готово. Папка: 111\2421252983
Парсю @yurieva_yuliya
Скачано: 112\1528985021\videos\01_DYsc1Hltb7m.mp4
Скачано: 112\1528985021\videos\02_DYr_nw_sFXI.mp4
Скачано: 112\1528985021\videos\03_DYrzJ1aM3FA.mp4

Готово. Папка: 112\1528985021
Парсю @al.alexandrovva
Скачано: 113\3611590613\videos\01_DXpLV7LMpIr.mp4
Скачано: 113\3611590613\videos\02_DXmIrhiMGsl.mp4
Скачано: 113\3611590613\videos\03_DXSGb7cgqZl.mp4

Готово. Папка: 113\3611590613
Парсю @lwowa.k
Скачано: 114\1101195106\videos\01_DYSSn6hs5Qz.mp4
Скачано: 114\1101195106\videos\02_DYFST54sean.mp4
Скачано: 114\1101195106\videos\03_DX9kmpBMlfV.mp4

Готово. Папка: 114\1101195106
Парсю @smailinng_
Скачано: 115\71816633586\videos\01_DYsJO7Zsc2w.mp4
Скачано: 115\71816633586\videos\02_DYesIGlMuDS.mp4
Скачано: 115\71816633586\videos\03_DYXP0iSsjfN.mp4

Готово. Папка: 115\71816633586
Парсю @its.aliiinna
Скачано: 116\5477072792\videos\01_DXuENHpjJfi.mp4
Скачано: 116\5477072792\videos\02_DYhFKwHSXvS.mp4
Скачано: 116\5477072792\videos\03_DYb3usVMetR.mp4

Готово. Папка: 116\5477072792
Парсю @nastyavasiiileva
Скачано: 117\61643196736\videos\01_DYp3tiPCXVQ.mp4
Скачано: 117\61643196736\videos\02_DYk0mDNCRrD.mp4
Скачано: 117\61643196736\videos\03_DYh6v4AC-Mj.mp4

Готово. Папка: 117\61643196736
Парсю @fffsonic

Готово. Папка: 118\1552323605
Парсю @eevameee
Скачано: 119\54523721163\videos\01_DYnewlZthkB.mp4
Скачано: 119\54523721163\videos\02_DYh8STsNp6e.mp4
Скачано: 119\54523721163\videos\03_DYXqeaKt043.mp4

Готово. Папка: 119\54523721163
Парсю @misdiminor
Скачано: 120\62340756471\videos\01_DYhNjMbC6oB.mp4
Скачано: 120\62340756471\videos\02_DYd5YhQCQfN.mp4
Скачано: 120\62340756471\videos\03_DYUqvO7sBWw.mp4

Готово. Папка: 120\62340756471
Парсю @krisbow.me
Скачано: 121\4856437838\videos\01_DT16gXgDGLJ.mp4
Скачано: 121\4856437838\videos\02_DQGfjLnDDuU.mp4
Скачано: 121\4856437838\videos\03_DYrm-eXsR_g.mp4

Готово. Папка: 121\4856437838
Парсю @lyaba_evochka
Скачано: 122\6747178743\videos\01_DTTCNavjYwZ.mp4
Скачано: 122\6747178743\videos\02_DXKKPCnNKzH.mp4
Скачано: 122\6747178743\videos\03_DXuxuI0tBRS.mp4

Готово. Папка: 122\6747178743
Парсю @lerochek.97
Скачано: 123\78017224571\videos\01_DYq2VTKM7sa.mp4
Скачано: 123\78017224571\videos\02_DYhWCjWMzU.mp4
Скачано: 123\78017224571\videos\03_DYbp0hcMtRm.mp4

Готово. Папка: 123\78017224571
Парсю @сторис

Готово. Папка: 124\D1_81_D1_82_D0_BE_D1_80_D0_B8_D1_81
Парсю @limataevaa

Готово. Папка: 125\limataevaa
Парсю @viktoris_dd
Скачано: 126\15843956175\videos\01_DUIdCIiCO5s.mp4
Скачано: 126\15843956175\videos\02_DS24JmqCMdp.mp4
Скачано: 126\15843956175\videos\03_DYr8FwBIWZy.mp4

Готово. Папка: 126\15843956175
Парсю @kamilkqs

Готово. Папка: 127\63168069388
Парсю @_rusllana__
Скачано: 128\8551542263\videos\01_DWMYCT0iPF9.mp4
Скачано: 128\8551542263\videos\02_DRSiPrYCMj4.mp4

Готово. Папка: 128\8551542263
Парсю @asia.anima

Готово. Папка: 129\asia.anima
Парсю @ann.tsvetkaaa
Скачано: 130\31385016132\videos\01_DYpqIkMoR1l.mp4
Скачано: 130\31385016132\videos\02_DYnDMncojEY.mp4
Скачано: 130\31385016132\videos\03_DYhUEpaIIof.mp4

Готово. Папка: 130\31385016132
Парсю @itsaiikaa
Скачано: 131\53697101575\videos\01_DObQKEYjE5z.mp4
Скачано: 131\53697101575\videos\02_DWrtwnzjGIA.mp4
Скачано: 131\53697101575\videos\03_DUJDnvBDOi.mp4

Готово. Папка: 131\53697101575
Парсю @_madsti_
Скачано: 132\6700108814\videos\01_DYrBeyIoaPD.mp4
Скачано: 132\6700108814\videos\02_DYofEj8SWRQ.mp4
Скачано: 132\6700108814\videos\03_DYnO0-aSoaP.mp4

Готово. Папка: 132\6700108814
Парсю @kosmanast
Скачано: 133\12129618675\videos\01_DYrjZkzoqId.mp4
Скачано: 133\12129618675\videos\02_DYkTeHiIpYS.mp4
Скачано: 133\12129618675\videos\03_DYX50MJIkOD.mp4

Готово. Папка: 133\12129618675
Парсю @ur.homeland
Скачано: 134\29046087244\videos\01_DYrmNhrTjYo.mp4
Скачано: 134\29046087244\videos\02_DYW8BLfuqe8.mp4
Скачано: 134\29046087244\videos\03_DYCh8pOqp_W.mp4

Готово. Папка: 134\29046087244
Парсю @samuraixaa
Скачано: 135\3876035889\videos\01_DYolY9RsGei.mp4
Скачано: 135\3876035889\videos\02_DYki_wGMLm5.mp4
Скачано: 135\3876035889\videos\03_DYSmj7vMj0u.mp4

Готово. Папка: 135\3876035889
Парсю @milkinadi
Скачано: 136\53090057342\videos\01_DRt1IfijJ82.mp4
Скачано: 136\53090057342\videos\02_DQ9h4xDjCx7.mp4
Скачано: 136\53090057342\videos\03_DPcXvKMjHxF.mp4

Готово. Папка: 136\53090057342
Парсю @sveta.subbo
Скачано: 137\58146336414\videos\01_DVyaaEejvVO.mp4
Скачано: 137\58146336414\videos\02_DYsY6AdM4Iq.mp4
Скачано: 137\58146336414\videos\03_DYp5jBBsiSz.mp4

Готово. Папка: 137\58146336414
Парсю @helen.redfield
Скачано: 138\73230099248\videos\01_DV_Uq5tjO1L.mp4
Скачано: 138\73230099248\videos\02_DVriltRDM-2.mp4
Скачано: 138\73230099248\videos\03_DOOyIrXjPcW.mp4

Готово. Папка: 138\73230099248
Парсю @flaw_rina
Скачано: 139\3112413117\videos\01_DYj8xPDIrLT.mp4
Скачано: 139\3112413117\videos\02_DYhflVMocnr.mp4
Скачано: 139\3112413117\videos\03_DYVVy_2g8x6.mp4

Готово. Папка: 139\3112413117
Парсю @ekatyys
Скачано: 140\2221944749\videos\01_DYfu5ipt6jX.mp4
Скачано: 140\2221944749\videos\02_DXuDn_-t9Hp.mp4
Скачано: 140\2221944749\videos\03_DXe_jiWjdAA.mp4

Готово. Папка: 140\2221944749
Парсю @twixi_twins
Скачано: 141\713947109\videos\01_DYr-i2ZIN4E.mp4
Скачано: 141\713947109\videos\02_DYpc4y-IAEX.mp4
Скачано: 141\713947109\videos\03_DYo4MV1IMSk.mp4

Готово. Папка: 141\713947109
Парсю @viktoriaevseevaa
Скачано: 142\80173419254\videos\01_DU_FqA0CIBI.mp4
Скачано: 142\80173419254\videos\02_DUm6BR5CBOy.mp4
Скачано: 142\80173419254\videos\03_DUSxPlkCNl-.mp4

Готово. Папка: 142\80173419254
Парсю @paalchikovva
Скачано: 143\7208317575\videos\01_DYkTOQ8i85C.mp4
Скачано: 143\7208317575\videos\02_DXra8KmgqEe.mp4

Готово. Папка: 143\7208317575
Парсю @miss.yana.liss
Скачано: 144\46427196728\videos\01_DYd_bfDBO7m.mp4
Скачано: 144\46427196728\videos\02_DYd9H6SBCxD.mp4
Скачано: 144\46427196728\videos\03_DYbmJeghgOU.mp4

Готово. Папка: 144\46427196728
Парсю @naturazova
Скачано: 145\11705163031\videos\01_DV9VIkhjVx8.mp4
Скачано: 145\11705163031\videos\02_DNLWtYWtcgO.mp4
Скачано: 145\11705163031\videos\03_DJ_yiuKNSVr.mp4

Готово. Папка: 145\11705163031
Парсю @di.li.ya_
Скачано: 146\3272541380\videos\01_DYpwjD0MrTU.mp4
Скачано: 146\3272541380\videos\02_DYpWce6stMN.mp4
Скачано: 146\3272541380\videos\03_DYpROl6MPFO.mp4

Готово. Папка: 146\3272541380
Парсю @_olga_purgina_

Готово. Папка: 147\olga_purgina
Парсю @joniboy_10
Скачано: 148\1622864753\videos\01_DYo_lrHqOxD.mp4
Скачано: 148\1622864753\videos\02_DYhYHh6qAGP.mp4
Скачано: 148\1622864753\videos\03_DYg5gMDqVZL.mp4

Готово. Папка: 148\1622864753
Парсю @ottorvaa
Скачано: 149\6954007047\videos\01_DYaNFnTqymt.mp4
Скачано: 149\6954007047\videos\02_DXxSYbUq6OT.mp4
Скачано: 149\6954007047\videos\03_DW4ynv8Cgvl.mp4

Готово. Папка: 149\6954007047
Парсю @rastsvetaii
Скачано: 150\9152309060\videos\01_DYrf3DFMLSu.mp4
Скачано: 150\9152309060\videos\02_DYopJ2eMm1G.mp4
Скачано: 150\9152309060\videos\03_DYkORkWMSLW.mp4

Готово. Папка: 150\9152309060
Парсю @maru.tsybulevskaya
Скачано: 151\283714002\videos\01_DVl0pFWgtuE.mp4
Скачано: 151\283714002\videos\02_DYr4dX8Cr7b.mp4
Скачано: 151\283714002\videos\03_DYrLW3ti6nq.mp4

Готово. Папка: 151\283714002
Парсю @olinelle.ro
Скачано: 152\68787622517\videos\01_DWtJ6cViJvB.mp4
Скачано: 152\68787622517\videos\02_DVV5OsHiJgF.mp4
Скачано: 152\68787622517\videos\03_DVV47kwCFbF.mp4

Готово. Папка: 152\68787622517
Парсю @raninen_indira
Скачано: 153\6755736778\videos\01_DYmO7a1tNI9.mp4
Скачано: 153\6755736778\videos\02_DYhEEjoNmRH.mp4
Скачано: 153\6755736778\videos\03_DYejydJNy79.mp4

Готово. Папка: 153\6755736778
Парсю @tasya.viyu_life
Скачано: 154\61752660798\videos\01_DWVN7DLCB7U.mp4
Скачано: 154\61752660798\videos\02_DWVNjqhCJ7s.mp4
Скачано: 154\61752660798\videos\03_DWVNEbWCBkv.mp4

Готово. Папка: 154\61752660798
Парсю @katya.bysinka
Скачано: 155\318912957\videos\01_DYjKgrHswT0.mp4
Скачано: 155\318912957\videos\02_DTkziw2jAmH.mp4
Скачано: 155\318912957\videos\03_DUF2zbUDKqg.mp4

Готово. Папка: 155\318912957
Парсю @helen_kayer
Скачано: 156\448653832\videos\01_DXRCq2RCnHi.mp4
Скачано: 156\448653832\videos\02_DYr7nYjJQOx.mp4
Скачано: 156\448653832\videos\03_DYpKXjAp27m.mp4

Готово. Папка: 156\448653832
Парсю @ksenka.mom
Скачано: 157\59163979399\videos\01_DYpKPBMMzBJ.mp4
Скачано: 157\59163979399\videos\02_DYl39Z5MDBy.mp4
Скачано: 157\59163979399\videos\03_DYjIjFWMUCf.mp4

Готово. Папка: 157\59163979399
Парсю @its.mary.shoppins
Скачано: 158\53779671230\videos\01_DUa-pvmiJc8.mp4
Скачано: 158\53779671230\videos\02_DTc8jIhiKlu.mp4
Скачано: 158\53779671230\videos\03_DTAasdXCEs3.mp4

Готово. Папка: 158\53779671230
Парсю @nastasidementeva
Скачано: 159\40502271825\videos\01_DYdCX0lMfPO.mp4
Скачано: 159\40502271825\videos\02_DYWnVi3sF2t.mp4
Скачано: 159\40502271825\videos\03_DYfCuUZMfuB.mp4

Готово. Папка: 159\40502271825
Парсю @grustnayaosoba
Скачано: 160\2270842300\videos\01_DYoqV-Xs9u2.mp4
Скачано: 160\2270842300\videos\02_DYiMYDfslkD.mp4
Скачано: 160\2270842300\videos\03_DYeXnE3MX_B.mp4

Готово. Папка: 160\2270842300
Парсю @shitova.bayer
Скачано: 161\1267370534\videos\01_DYrjp-PIs7B.mp4
Скачано: 161\1267370534\videos\02_DYmU0F_IGyU.mp4
Скачано: 161\1267370534\videos\03_DYjtc6oILRm.mp4

Готово. Папка: 161\1267370534
Парсю @marenela_beauty
Скачано: 162\9614970988\videos\01_DYg_3_NI6Ex.mp4
Скачано: 162\9614970988\videos\02_DYeXZUKoWpz.mp4
Скачано: 162\9614970988\videos\03_DYUFZAlIjK6.mp4

Готово. Папка: 162\9614970988
Парсю @natalia.lapina_
Скачано: 163\489359212\videos\01_DYrcS0qqBvE.mp4
Скачано: 163\489359212\videos\02_DYmaszDqv8F.mp4
Скачано: 163\489359212\videos\03_DXpcJzoClKg.mp4

Готово. Папка: 163\489359212
Парсю @svetamlg
Скачано: 164\79994069535\videos\01_DW1oeAXDAoC.mp4
Скачано: 164\79994069535\videos\02_DW1cfwLDMrv.mp4
Скачано: 164\79994069535\videos\03_DWrbAnnjNhe.mp4

Готово. Папка: 164\79994069535
Парсю @anya___vasina
Скачано: 165\345570054\videos\01_DYrysG8MXhV.mp4
Скачано: 165\345570054\videos\02_DYrIFexuru6.mp4
Скачано: 165\345570054\videos\03_DYhCwaVOpWL.mp4

Готово. Папка: 165\345570054
Парсю @mordovochka_katrin
Скачано: 166\1552863551\videos\01_DBjAMK9Iu9E.mp4
Скачано: 166\1552863551\videos\02_C-7jxr4o63n.mp4
Скачано: 166\1552863551\videos\03_DYrjD6tIQ9A.mp4

Готово. Папка: 166\1552863551
Парсю @nikalina_life
Скачано: 167\72735710584\videos\01_DYmGYGyMA9c.mp4
Скачано: 167\72735710584\videos\02_DYj_n8lMnYF.mp4
Скачано: 167\72735710584\videos\03_DYhcVHuMojH.mp4

Готово. Папка: 167\72735710584
Парсю @hi.natasmith
Скачано: 168\293689871\videos\01_CmuPGCsMonE.mp4
Скачано: 168\293689871\videos\02_DYpOyQ3tFiL.mp4
Скачано: 168\293689871\videos\03_DYo4JiENig0.mp4

Готово. Папка: 168\293689871
Парсю @lifaanteva

ValueError: Нужна ссылка на профиль, а не на пост/reel/story

In [31]:
for i in tqdm(range(354, 419)):
    save_profile(inst_dict[str(i)], str(i))

  0%|          | 0/65 [00:00<?, ?it/s]

Парсю @probbbeauty
Скачано: 354\982785540\videos\01_C9IgI5EN2a0.mp4
Скачано: 354\982785540\videos\02_CjkjJ_TgEyo.mp4
Скачано: 354\982785540\videos\03_CjX80cLAMH5.mp4

Готово. Папка: 354\982785540
Парсю @dianaashikhova
Скачано: 355\3719364469\videos\01_DYmvLGOIA8s.mp4
Скачано: 355\3719364469\videos\02_DYjwAhdIPXE.mp4
Скачано: 355\3719364469\videos\03_DYhgMaJIvwH.mp4

Готово. Папка: 355\3719364469
Парсю @sweetpirat
Скачано: 356\227367628\videos\01_DXq5ROtxpX8.mp4
Скачано: 356\227367628\videos\02_C-4wO_1qZ1I.mp4
Скачано: 356\227367628\videos\03_DYpWMhmIjvO.mp4

Готово. Папка: 356\227367628
Парсю @butorovva
Скачано: 357\57267127212\videos\01_DYHf_tZMYqK.mp4
Скачано: 357\57267127212\videos\02_DXwYGfnsFdb.mp4
Скачано: 357\57267127212\videos\03_DXubp6pDPOO.mp4

Готово. Папка: 357\57267127212
Парсю @petrova.blogs
Скачано: 358\9147802127\videos\01_DYXhnuqgX_n.mp4
Скачано: 358\9147802127\videos\02_DYXJ5J0AVLB.mp4
Скачано: 358\9147802127\videos\03_DYSTQRggdvy.mp4

Готово. Папка: 358\9147802127
Парсю @emilyloker
Скачано: 359\869384139\videos\01_DYl6UEHNMVv.mp4
Скачано: 359\869384139\videos\02_DYZOtObpaQK.mp4
Скачано: 359\869384139\videos\03_DYXgCpANYsB.mp4

Готово. Папка: 359\869384139
Парсю @aallua
Скачано: 360\2128139930\videos\01_DYrZLsWt2Fl.mp4
Скачано: 360\2128139930\videos\02_DYmxJy1tO-9.mp4
Скачано: 360\2128139930\videos\03_DYmSkpWM5JL.mp4

Готово. Папка: 360\2128139930
Парсю @anytamay

Готово. Папка: 361\anytamay
Парсю @lubakaka
Скачано: 362\1052157174\videos\01_DUGGZ8VjGKH.mp4
Скачано: 362\1052157174\videos\02_DKxPktJNA4N.mp4
Скачано: 362\1052157174\videos\03_DV_eUDXjGWl.mp4

Готово. Папка: 362\1052157174
Парсю @callmegelik

Готово. Папка: 363\34858188446
Парсю @alinaa.korneenko
Скачано: 364\3051120789\videos\01_DPNATIQiD7u.mp4
Скачано: 364\3051120789\videos\02_DSYZdUoCFPY.mp4
Скачано: 364\3051120789\videos\03_DSYWlvxiA9M.mp4

Готово. Папка: 364\3051120789
Парсю @xana.solod
Скачано: 365\44689897074\videos\01_DVvjvzCCrzC.mp4
Скачано: 365\44689897074\videos\02_DWqWExvDTEA.mp4
Скачано: 365\44689897074\videos\03_DYmFzWKN98U.mp4

Готово. Папка: 365\44689897074
Парсю @sosiskinaa
Скачано: 366\1326692482\videos\01_DYr63RksVtL.mp4
Скачано: 366\1326692482\videos\02_DYptofxsW3l.mp4
Скачано: 366\1326692482\videos\03_DYpqSeqsWze.mp4

Готово. Папка: 366\1326692482
Парсю @angelinchab

Готово. Папка: 367\angelinchab
Парсю @hodorrovvaa
Скачано: 368\42559987677\videos\01_DYl0mH6ME_5.mp4
Скачано: 368\42559987677\videos\02_DXd8_qJjITE.mp4
Скачано: 368\42559987677\videos\03_DWgAEa8DDD-.mp4

Готово. Папка: 368\42559987677
Парсю @glow.iren
Скачано: 369\55460828647\videos\01_DYR525gMRVw.mp4
Скачано: 369\55460828647\videos\02_DYHHuZHiyys.mp4
Скачано: 369\55460828647\videos\03_DX9HfaFMaT8.mp4

Готово. Папка: 369\55460828647
Парсю @alinamilevskaya
Скачано: 370\14245869\videos\01_DYsCqfbsWt5.mp4
Скачано: 370\14245869\videos\02_DYmwodkMbYb.mp4
Скачано: 370\14245869\videos\03_DYkgEoJuq1P.mp4

Готово. Папка: 370\14245869
Парсю @princesska_mua
Скачано: 371\55345069491\videos\01_DYEOTFgsU6u.mp4
Скачано: 371\55345069491\videos\02_DYEOEmfsGwZ.mp4
Скачано: 371\55345069491\videos\03_DX3h0i-sRjy.mp4

Готово. Папка: 371\55345069491
Парсю @wowantonova
Скачано: 372\2033809447\videos\01_DYakno4PV22.mp4
Скачано: 372\2033809447\videos\02_DXcJ-ssD5B6.mp4
Скачано: 372\2033809447\videos\03_DXOo8txD_92.mp4

Готово. Папка: 372\2033809447
Парсю @lucyseventy

Готово. Папка: 373\lucyseventy
Парсю @hey_iamkris
Скачано: 374\59894355350\videos\01_DYpPTDesOqA.mp4
Скачано: 374\59894355350\videos\02_DYksH1rsDvn.mp4
Скачано: 374\59894355350\videos\03_DYe3oO2MZcA.mp4

Готово. Папка: 374\59894355350
Парсю @vvalerievi
Скачано: 375\2199849293\videos\01_DYm5qr9Md6N.mp4
Скачано: 375\2199849293\videos\02_DYfeLQIMs2R.mp4
Скачано: 375\2199849293\videos\03_DYb2XKTMnep.mp4

Готово. Папка: 375\2199849293
Парсю @veka.move
Скачано: 376\28624705943\videos\01_DYp3Zs2N9_P.mp4
Скачано: 376\28624705943\videos\02_DW3vRtXjQxw.mp4

Готово. Папка: 376\28624705943
Парсю @alyonakush
Скачано: 377\3428434367\videos\01_DYsTBLAI96l.mp4
Скачано: 377\3428434367\videos\02_DYpnOL5oZBh.mp4
Скачано: 377\3428434367\videos\03_DYQE85copAh.mp4

Готово. Папка: 377\3428434367
Парсю @avanesik
Скачано: 378\51602634698\videos\01_DYQHtZVIYeG.mp4
Скачано: 378\51602634698\videos\02_DYE7C2cIYU.mp4
Скачано: 378\51602634698\videos\03_DXosov9iHXk.mp4

Готово. Папка: 378\51602634698
Парсю @an.aleksaandrova
Скачано: 379\1114149917\videos\01_DNJJ2xssb6j.mp4
Скачано: 379\1114149917\videos\02_DIM-2ujoGV2.mp4
Скачано: 379\1114149917\videos\03_DKot-TkIYFR.mp4

Готово. Папка: 379\1114149917
Парсю @kristina_one
Скачано: 380\436822700\videos\01_DSZnUyuCA0c.mp4
Скачано: 380\436822700\videos\02_DYsjk6mo6nP.mp4
Скачано: 380\436822700\videos\03_DYribO6Ijnx.mp4

Готово. Папка: 380\436822700
Парсю @rin.tikh
Скачано: 381\5367948822\videos\01_DQqYtNgDISu.mp4
Скачано: 381\5367948822\videos\02_DVJVOEGjKbE.mp4
Скачано: 381\5367948822\videos\03_DSRhgP1jJzp.mp4

Готово. Папка: 381\5367948822
Парсю @yana.ermolay
Скачано: 382\276918011\videos\01_DYq0jKtsxFQ.mp4
Скачано: 382\276918011\videos\02_DYpXjrmsL6c.mp4
Скачано: 382\276918011\videos\03_DYl7Ds3s6G7.mp4

Готово. Папка: 382\276918011
Парсю @kostushaa
Скачано: 383\969941229\videos\01_DYr0YIeIK-r.mp4
Скачано: 383\969941229\videos\02_DYW21vKhjJv.mp4
Скачано: 383\969941229\videos\03_DYUoDtchiQB.mp4

Готово. Папка: 383\969941229
Парсю @noova.stylist
Скачано: 384\48851623975\videos\01_DYp7fK0x883.mp4
Скачано: 384\48851623975\videos\02_DYp7GdfxAX5.mp4
Скачано: 384\48851623975\videos\03_DYp4wcAxpk-.mp4

Готово. Папка: 384\48851623975
Парсю @dmezrina
Скачано: 385\327487559\videos\01_DYr_W2Nsz17.mp4
Скачано: 385\327487559\videos\02_DYo2D_RM_nG.mp4
Скачано: 385\327487559\videos\03_DYgto7uMGnc.mp4

Готово. Папка: 385\327487559
Парсю @golodzlo
Скачано: 386\1242892861\videos\01_DYsF-43qU-.mp4
Скачано: 386\1242892861\videos\02_DYqNmDQKdY8.mp4
Скачано: 386\1242892861\videos\03_DYqKLxwqZij.mp4

Готово. Папка: 386\1242892861
Парсю @kondina_beauty
Скачано: 387\48102346492\videos\01_DYr6MpKNo1Y.mp4
Скачано: 387\48102346492\videos\02_DYqDQMatx3q.mp4
Скачано: 387\48102346492\videos\03_DYqB56ftk_r.mp4

Готово. Папка: 387\48102346492
Парсю @tanya_amurskaya
Скачано: 388\227658246\videos\01_DQMaZvPDZYA.mp4
Скачано: 388\227658246\videos\02_DVQsjaMDenH.mp4
Скачано: 388\227658246\videos\03_DQmdvQFDaeM.mp4

Готово. Папка: 388\227658246
Парсю @veili_ro
Скачано: 389\6841659948\videos\01_DWoTBKdAmkm.mp4
Скачано: 389\6841659948\videos\02_DWl3D-GAvzN.mp4
Скачано: 389\6841659948\videos\03_DWg3aM7AqW6.mp4

Готово. Папка: 389\6841659948
Парсю @z.vivvy

Готово. Папка: 390\z.vivvy
Парсю @margo.lik_
Скачано: 391\65226709055\videos\01_DYpI27Bqg4N.mp4
Скачано: 391\65226709055\videos\02_DYnP7vkuefs.mp4
Скачано: 391\65226709055\videos\03_DYmu0YcKaMU.mp4

Готово. Папка: 391\65226709055
Парсю @kat.malkova
Скачано: 392\4835858096\videos\01_DSR69K9jYOH.mp4
Скачано: 392\4835858096\videos\02_DYgqTEHNY2X.mp4
Скачано: 392\4835858096\videos\03_DYSM4ONN3oS.mp4

Готово. Папка: 392\4835858096
Парсю @heeylls

Готово. Папка: 393\heeylls
Парсю @miss_alyona666
Скачано: 394\974535424\videos\01_DYpmIDnt1po.mp4
Скачано: 394\974535424\videos\02_DYkem0OORh4.mp4
Скачано: 394\974535424\videos\03_DYPSwBoNI6Y.mp4

Готово. Папка: 394\974535424
Парсю @lllll10.10.lllll
Скачано: 395\7164432222\videos\01_DX8mqt-oNEH.mp4
Скачано: 395\7164432222\videos\02_DXhXuZFCIiE.mp4
Скачано: 395\7164432222\videos\03_DVoNO3vjYf8.mp4

Готово. Папка: 395\7164432222
Парсю @jeny_lolua
Скачано: 396\236562594\videos\01_DDdHo5_ijyr.mp4
Скачано: 396\236562594\videos\02_DVtEhozjC1s.mp4

Готово. Папка: 396\236562594
Парсю @kate.provisual
Скачано: 397\2100940447\videos\01_DYbk6SisE1g.mp4
Скачано: 397\2100940447\videos\02_DYT50pcsXCE.mp4
Скачано: 397\2100940447\videos\03_DYCFcW1M764.mp4

Готово. Папка: 397\2100940447
Парсю @olechka_alexandrovaa
Скачано: 398\261376543\videos\01_DYmEpVVgmZG.mp4
Скачано: 398\261376543\videos\02_DYrKv7aAddK.mp4
Скачано: 398\261376543\videos\03_DYmsUaOMSPK.mp4

Готово. Папка: 398\261376543
Парсю @zilya_vaf
Скачано: 399\59531661854\videos\01_DYm3sfroGTD.mp4
Скачано: 399\59531661854\videos\02_DX413jcsTut.mp4
Скачано: 399\59531661854\videos\03_DX1HyCfoajy.mp4

Готово. Папка: 399\59531661854
Парсю @veronika_kuimova
Скачано: 400\1190834746\videos\01_DYWlzvLNfpH.mp4
Скачано: 400\1190834746\videos\02_DYMchWeN4DV.mp4

Готово. Папка: 400\1190834746
Парсю @palin_beskov
Скачано: 401\276138252\videos\01_DYovjdmiKCD.mp4
Скачано: 401\276138252\videos\02_DYZUv_jCzTj.mp4
Скачано: 401\276138252\videos\03_DYR-0i-CN6z.mp4

Готово. Папка: 401\276138252
Парсю @anyushina_anna
Скачано: 402\472256263\videos\01_DYreLV9OLFs.mp4
Скачано: 402\472256263\videos\02_DYq7zUbKNXe.mp4
Скачано: 402\472256263\videos\03_DYpAKJcK1qJ.mp4

Готово. Папка: 402\472256263
Парсю @oh__mari
Скачано: 403\349863440\videos\01_DXNH0oxuI2n.mp4
Скачано: 403\349863440\videos\02_DYknpeAOQy4.mp4
Скачано: 403\349863440\videos\03_DYhSWXHNir.mp4

Готово. Папка: 403\349863440
Парсю @yanaa.ten
Скачано: 404\7275587139\videos\01_DTxS4SvjDbN.mp4
Скачано: 404\7275587139\videos\02_DQx89ieDB1K.mp4
Скачано: 404\7275587139\videos\03_DQp6k6HCGPZ.mp4

Готово. Папка: 404\7275587139

ValueError: Нужна ссылка на профиль, а не на пост/reel/story

In [35]:
for i in tqdm(range(406, 419)):
    save_profile(inst_dict[str(i)], str(i))

  0%|          | 0/13 [00:00<?, ?it/s]

Парсю @_ayawaska__
Скачано: 406\67232071868\videos\01_DVv0E-ZCB4g.mp4
Скачано: 406\67232071868\videos\02_DVoHDvOiJ0-.mp4
Скачано: 406\67232071868\videos\03_DVL4JIxiPX5.mp4

Готово. Папка: 406\67232071868
Парсю @pavlowna
Скачано: 407\2010092419\videos\01_DXRQrpishwp.mp4
Скачано: 407\2010092419\videos\02_DWY0kOojArw.mp4
Скачано: 407\2010092419\videos\03_DVyaLlKjGgq.mp4

Готово. Папка: 407\2010092419
Парсю @olya.dobrynina
Скачано: 408\332737684\videos\01_DYsUzV_Opa6.mp4
Скачано: 408\332737684\videos\02_DYsJ79uO8qp.mp4
Скачано: 408\332737684\videos\03_DYpgjxbIygC.mp4

Готово. Папка: 408\332737684
Парсю @ksu_sfx
Скачано: 409\35714988411\videos\01_DXgdG3BAfPY.mp4
Скачано: 409\35714988411\videos\02_DXeMOsYgUto.mp4
Скачано: 409\35714988411\videos\03_DXWMoPmAfb6.mp4

Готово. Папка: 409\35714988411
Парсю @veronika.kukina
Скачано: 410\3519200391\videos\01_DUVyOndEpwl.mp4

Готово. Папка: 410\3519200391
Парсю @cwestere
Скачано: 411\49397259211\videos\01_DYo7jLpI86g.mp4
Скачано: 411\49397259211\videos\02_DYoUDK-of2P.mp4
Скачано: 411\49397259211\videos\03_DYmV71VoQGM.mp4

Готово. Папка: 411\49397259211
Парсю @koozhevnikovaa
Скачано: 412\68349338016\videos\01_DWljUPtDmNZ.mp4
Скачано: 412\68349338016\videos\02_DWlT3P9Dnhq.mp4
Скачано: 412\68349338016\videos\03_DU3X4cWDkwm.mp4

Готово. Папка: 412\68349338016
Парсю @bylinskaya_
Скачано: 413\65144252857\videos\01_DYcQQ5tNqyL.mp4
Скачано: 413\65144252857\videos\02_DYbtUWmNPb4.mp4
Скачано: 413\65144252857\videos\03_DYMcGk7tNpt.mp4

Готово. Папка: 413\65144252857
Парсю @anniesstorie
Скачано: 414\635997661\videos\01_DYsZz-kRUnz.mp4
Скачано: 414\635997661\videos\02_DYARDYvsZAn.mp4
Скачано: 414\635997661\videos\03_DXNHCsLDOjC.mp4

Готово. Папка: 414\635997661
Парсю @lena.bel
Не скачалось: https://instagram.fcps3-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQNYvv7a7kH_Yh5ywsbzu1FgZ...
Ошибка: HTTPSConnectionPool(host='instagram.fcps3-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t2/f2/m86/AQNYvv7a7kH_Yh5ywsbzu1FgZ60r5RSxYdnQV2Jbfrh7MhJ_i04advcKigYRjQ-6-wKtK8B8lk-ywlQY9QLCPccxFJfscg_tYhpNUzY.mp4?_nc_cat=100&_nc_oc=AdphZpox_8cE1LcI7QMLiQvwVVTKWTkERKkD1wiC5QIrsAVmPSiuVLMgFXiJ0-HfswNHjv034hplrAxEq9Xv-fIj&_nc_sid=5e9851&_nc_ht=instagram.fcps3-1.fna.fbcdn.net&_nc_ohc=snN0zHJe9BEQ7kNvwHu5AID&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NTY4Mjk2MjgxMDIwMDAsImFzc2V0X2FnZV9kYXlzIjo1NCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjYzLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=79c4861f212fa702&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC85NDQyQUY1NzhEQTE2OUIyRjA1NTU5QkQ2NDZFNzhBQl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0MzNEQ0ODM2RUYxMjY2Nzk3NTIwMDc4MzczOTFFNjk0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbg1bO0hunlPxUCKAJDMywXQE-u2RaHKwIYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=vB7ZxQtMIsPind5l6fhHPg&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af7ISj0cuuZpXCwrqlOe82sEPxh2q3xxBjyBH9xrIDmPzA&oe=6A145D25 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DWg9OUUDhP_
Не скачалось: https://instagram.fcps3-1.fna.fbcdn.net/o1/v/t16/f2/m69/AQOZSssgeOvqrML9bI4fxbtX...
Ошибка: HTTPSConnectionPool(host='instagram.fcps3-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t16/f2/m69/AQOZSssgeOvqrML9bI4fxbtX7cVHK6vDnsHkAGXmUDDuvsIt9yfS2UL6-JWWaY-OJexUoCGnBcK2TpOP4672SMbZ.mp4?strext=1&_nc_cat=100&_nc_oc=AdrdILFIJZQa8B2FLGsYa8-CNlsB0PDRJenmQAEpqNW0Rsxw1lGM95gQFLknV6mhaVLgVCgzd94FPWOaqvV_9TyL&_nc_sid=5e9851&_nc_ht=instagram.fcps3-1.fna.fbcdn.net&_nc_ohc=9qoasrBh_DwQ7kNvwG8VJHs&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NTEyODc0NzkxMDIwMDAsImFzc2V0X2FnZV9kYXlzIjo3NiwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=60ba4934a56d839f&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HQzlqb0NiQ3c3eENkOGtDQUIyR2lRblRXNkpVYnNwVEFRQUYVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0FBNDcyRjA1RTVDOTkxMzQ0QjdFODVBMzA2NUIyMzg5X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbgqJ-XuqbjPxUCKAJDMywXQBkzMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=vB7ZxQtMIsPind5l6fhHPg&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af4jKFnbEVVfg1EbN38vxRzdC2s8SVsMdMKqtFOAB_YN1w&oe=6A186580 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DVoGjUjjJ_N
Не скачалось: https://instagram.fcps4-1.fna.fbcdn.net/o1/v/t16/f2/m69/AQNjbPU6at-SOeR8XkF7ucUx...
Ошибка: HTTPSConnectionPool(host='instagram.fcps4-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t16/f2/m69/AQNjbPU6at-SOeR8XkF7ucUxM3w3yyd_ErOtpZ-AT_5gbKLp7KUHwwgbWO_Lw8h51Ti_6isaOALg26BnzjMpEHXa.mp4?strext=1&_nc_cat=111&_nc_oc=AdoTUOo-F-T6Zlc_0k7Xkovj4j5G2YPeU-foidrXoGTMTSFXMTWPeJg1l37mgaoDVLy6UuMI28rXuikCbtIYkt_B&_nc_sid=5e9851&_nc_ht=instagram.fcps4-1.fna.fbcdn.net&_nc_ohc=rDi1P4T19U4Q7kNvwHztu2y&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NDkwOTY4OTcxMDIwMDAsImFzc2V0X2FnZV9kYXlzIjo4NSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=da0e6b959edfcf53&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HSlBGV3liZzdEaExXS0lQQUdrTExzUWJpbEJEYnNwVEFRQUYVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0NCNDhEMzFCQTk5ODQxNzgxOTJENUY4MDQ1NkU0NTg3X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbggrqJ-abiPxUCKAJDMywXQBhDlYEGJN0YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=vB7ZxQtMIsPind5l6fhHPg&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af4-Y76f9bUtHj-HyCWRJ-FYLCbdNacbE44Yx1XJOoisVw&oe=6A1872D1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DVQ96I1jE30

Готово. Папка: 415\8890246681
Парсю @alina.alms
Не скачалось: https://instagram.fcps4-1.fna.fbcdn.net/o1/v/t2/f2/m367/AQNi9QvA_plVdwPySOo1iP-s...
Ошибка: HTTPSConnectionPool(host='instagram.fcps4-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t2/f2/m367/AQNi9QvA_plVdwPySOo1iP-sKJ_lBn29QBB1gCJbws1dkFZzmaN74LH6LRGR_Dbe-QjMaelmZzag5N7-jxUU2Vmip6rET4Yxv7YsCvk.mp4?_nc_cat=103&_nc_oc=Adr5JA9UvRA182OF4A69Yp39yIV8Rx7RhffpFSEE7usLHXm1PwqKDuTy2-lcT8YJWFdSbBuZhRuCGn3UvR1jXegO&_nc_sid=5e9851&_nc_ht=instagram.fcps4-1.fna.fbcdn.net&_nc_ohc=ODOSkpZl6MMQ7kNvwE4OBOS&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTcyNjgwMTEyODE4ODY0MiwiYXNzZXRfYWdlX2RheXMiOjM4OCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=139ac3db1d8b0f2b&_nc_vs=HBksFQIYQGlnX2VwaGVtZXJhbC9CMjRBMjAzRTBBMTUzRUU0QjkyRTc3QzUwRjI0ODk4Nl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC82NDQzNDQ2NDg0MzQ1MjhfMzkwNTEyODM0Njc5NzQxODQ3OC5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmxKu__YahkQYVAigCQzMsF0AazMzMzMzNGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2XmnQEA&_nc_gid=k-y4uZFHPBHnXEWLD9thKw&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af7yPcRox3UJIdt8opzL29vrpJ9VzLWXfvP-OmX9a-wNJg&oe=6A18707C (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DJFQI5zIPeY
Не скачалось: https://instagram.fcps3-1.fna.fbcdn.net/o1/v/t16/f2/m69/AQNjsJgnuVSmKs-W_x3U7w6k...
Ошибка: HTTPSConnectionPool(host='instagram.fcps3-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t16/f2/m69/AQNjsJgnuVSmKs-W_x3U7w6kwIpxJgoXawefQ76xAI-iGsCPUDWohBlSC5USSf6qgiVuZPDHZxoVdAoReWvAgYas.mp4?strext=1&_nc_cat=109&_nc_oc=Adrzrs-w09_XURDlpYFrUVhGqncTEnFqziwAsCTnyiqm1q2Ifl7lqOWfurjq89feCrFlnBClK2UWTVUeB5H3MNYa&_nc_sid=5e9851&_nc_ht=instagram.fcps3-1.fna.fbcdn.net&_nc_ohc=_84D8HruP7gQ7kNvwHzE4sx&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTg1NjkzNjgwODQwNDMxMjksImFzc2V0X2FnZV9kYXlzIjo2NSwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjEwLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=c61d117ce18bbc7&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HTFVJM1NZUkVPXzhJc29DQUh0WlljRERWeGdYYnNwVEFRQUYVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzUwNEZBREY5NTUyNTRCQzI3OUFGM0VEOEVDMDc0QTg1X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACby1dLFva_8QRUCKAJDMywXQCVEGJN0vGoYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=k-y4uZFHPBHnXEWLD9thKw&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af6yO6OfRsVzSmGyD2pzSzl4eXunByWrldhkik9-WZihBw&oe=6A186297 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DWEd-i5DJv4
Не скачалось: https://instagram.fcps4-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQPP6HvUYIXZ155x7APcI3JqE...
Ошибка: HTTPSConnectionPool(host='instagram.fcps4-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t2/f2/m86/AQPP6HvUYIXZ155x7APcI3JqEhtTqOdZ5JzQrqti3QFe5b5ZFWrpyKe3Fr8qIkj6dQDEzf6EZV97hJObmVHDuRPGm2CvB6_a9kgB7zA.mp4?_nc_cat=105&_nc_oc=AdrBRG7-ksL82Ts-o-M9GqxzPrTXit05viD7AX7yaknudmWJaG0ooHez9FZY_EKf4PWyE5hXOLnflOTKi6-cz4F7&_nc_sid=5e9851&_nc_ht=instagram.fcps4-1.fna.fbcdn.net&_nc_ohc=E-_Bxg4OJXYQ7kNvwE527eG&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MjY4MDIzODQxNzYwODA2NDMsImFzc2V0X2FnZV9kYXlzIjoxMCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjQsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=ede4035a14f6e0e6&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9EODRDODRCNkEwQzk3MzU3MjBDQkU1MjZGMjVDQ0FCNl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzJCNEYwM0VBOENEMTM4MEZGMjkwNzQ2ODQzQzVEMkExX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaGnJe_i6icXxUCKAJDMywXQBO7ZFocrAgYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZeadAQA&_nc_gid=k-y4uZFHPBHnXEWLD9thKw&_nc_ss=7a3ba&_nc_zt=28&oh=00_Af6ErHICpMjDu0hB3JB16FM9LNvA6INRhj9vDu9GxC4upA&oe=6A145686 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)')))
Не скачалось видео DYSTydPN1sb

Готово. Папка: 416\242027128
Парсю @nebalashova

Готово. Папка: 417\nebalashova
Парсю @ryzh.nika
Скачано: 418\3658659194\videos\01_DYpIMyEPNmV.mp4
Скачано: 418\3658659194\videos\02_DYj0QzMtsBa.mp4
Скачано: 418\3658659194\videos\03_DYexOWHt6rm.mp4

Готово. Папка: 418\3658659194